data(posh_brown_bag,[record(5,dim_coral_bag),record(1,plaid_blue_bag),record(2,faded_bronze_bag),record(2,light_black_bag)]).
data(vibrant_lime_bag,[record(3,dull_lavender_bag),record(3,dim_crimson_bag),record(3,mirrored_lavender_bag),record(2,muted_cyan_bag)]).
data(clear_olive_bag,[record(1,wavy_gold_bag),record(4,dim_lime_bag),record(3,dull_tomato_bag),record(5,dark_turquoise_bag)]).
data(dark_purple_bag,[record(5,striped_tan_bag),record(5,bright_cyan_bag),record(3,dark_indigo_bag)]).
data(posh_maroon_bag,[record(3,bright_salmon_bag)]).
data(dim_violet_bag,[record(1,pale_violet_bag),record(1,bright_gold_bag)]).
data(clear_gray_bag,[record(1,bright_gray_bag)]).
data(light_brown_bag,[record(1,light_aqua_bag),record(4,vibrant_yellow_bag),record(5,posh_green_bag)]).
data(muted_yellow_bag,[record(4,drab_bronze_bag),record(2,dull_gray_bag),record(2,vibrant_olive_bag)]).
data(striped_orange_bag,[record(4,mirrored_brown_bag),record(4,plaid_olive_bag)]).
data(striped_turquoise_bag,[record(2,muted_indigo_bag)]).
data(mirrored_crimson_bag,[no_other_bags]).
data(muted_teal_bag,[record(4,striped_purple_bag)]).
data(light_purple_bag,[record(5,dim_coral_bag),record(3,striped_teal_bag),record(1,dim_teal_bag),record(4,clear_gold_bag)]).
data(shiny_olive_bag,[record(2,muted_cyan_bag),record(1,wavy_white_bag),record(4,light_chartreuse_bag),record(4,mirrored_indigo_bag)]).
data(dim_black_bag,[record(4,wavy_lavender_bag),record(5,drab_blue_bag)]).
data(pale_maroon_bag,[record(5,vibrant_olive_bag)]).
data(dotted_maroon_bag,[record(2,faded_lime_bag),record(1,clear_turquoise_bag)]).
data(light_aqua_bag,[record(5,dark_brown_bag),record(2,shiny_gold_bag)]).
data(vibrant_beige_bag,[record(2,pale_cyan_bag),record(2,dotted_crimson_bag),record(2,vibrant_teal_bag)]).
data(striped_white_bag,[record(2,shiny_gold_bag)]).
data(light_orange_bag,[record(1,dim_coral_bag),record(2,vibrant_coral_bag)]).
data(dull_green_bag,[record(1,plaid_green_bag)]).
data(shiny_turquoise_bag,[record(3,striped_olive_bag),record(3,drab_cyan_bag),record(2,dim_lime_bag),record(3,muted_brown_bag)]).
data(posh_chartreuse_bag,[record(2,mirrored_indigo_bag),record(3,light_black_bag),record(4,mirrored_bronze_bag),record(3,light_gold_bag)]).
data(drab_green_bag,[no_other_bags]).
data(drab_plum_bag,[record(3,pale_blue_bag),record(4,dull_teal_bag),record(1,striped_violet_bag)]).
data(muted_indigo_bag,[record(5,dark_turquoise_bag)]).
data(pale_beige_bag,[record(4,wavy_gray_bag),record(4,faded_lime_bag),record(4,bright_beige_bag),record(1,plaid_violet_bag)]).
data(vibrant_blue_bag,[record(5,drab_tan_bag),record(4,dull_tomato_bag)]).
data(vibrant_turquoise_bag,[record(1,posh_lavender_bag)]).
data(clear_maroon_bag,[record(2,shiny_brown_bag)]).
data(bright_crimson_bag,[record(2,faded_indigo_bag),record(4,dull_teal_bag)]).
data(wavy_tan_bag,[record(5,dotted_fuchsia_bag),record(2,muted_fuchsia_bag),record(2,light_white_bag)]).
data(dim_teal_bag,[no_other_bags]).
data(faded_plum_bag,[record(1,faded_cyan_bag),record(4,dull_lime_bag),record(2,vibrant_cyan_bag)]).
data(vibrant_orange_bag,[record(3,plaid_salmon_bag),record(3,mirrored_yellow_bag)]).
data(posh_gray_bag,[record(4,dark_indigo_bag),record(3,light_blue_bag),record(5,light_red_bag),record(3,pale_aqua_bag)]).
data(dull_aqua_bag,[record(1,dark_fuchsia_bag),record(2,faded_silver_bag)]).
data(light_bronze_bag,[record(1,muted_indigo_bag)]).
data(pale_coral_bag,[record(1,plaid_tomato_bag),record(4,faded_plum_bag),record(2,mirrored_turquoise_bag),record(1,posh_lavender_bag)]).
data(pale_lime_bag,[record(1,dotted_gray_bag),record(3,mirrored_coral_bag),record(5,pale_silver_bag),record(5,mirrored_yellow_bag)]).
data(shiny_violet_bag,[record(2,faded_orange_bag),record(3,muted_indigo_bag),record(5,muted_violet_bag)]).
data(vibrant_coral_bag,[record(3,posh_fuchsia_bag),record(1,dim_coral_bag),record(4,faded_gold_bag),record(5,dotted_violet_bag)]).
data(dim_magenta_bag,[record(3,pale_purple_bag),record(4,plaid_turquoise_bag),record(2,bright_lavender_bag)]).
data(dull_brown_bag,[record(5,vibrant_turquoise_bag),record(3,faded_bronze_bag),record(3,striped_tan_bag),record(4,dim_gold_bag)]).
data(bright_brown_bag,[record(5,dark_teal_bag),record(2,posh_indigo_bag),record(4,drab_fuchsia_bag)]).
data(dim_tan_bag,[record(4,dark_magenta_bag),record(1,clear_blue_bag),record(2,vibrant_olive_bag)]).
data(plaid_black_bag,[record(4,pale_indigo_bag),record(3,clear_gold_bag)]).
data(muted_plum_bag,[record(3,faded_brown_bag),record(5,drab_orange_bag),record(5,dull_turquoise_bag)]).
data(light_tomato_bag,[record(3,wavy_coral_bag),record(2,drab_green_bag),record(2,dull_crimson_bag)]).
data(dull_cyan_bag,[record(1,clear_blue_bag),record(3,clear_yellow_bag)]).
data(clear_turquoise_bag,[record(5,pale_black_bag),record(1,pale_brown_bag),record(5,bright_beige_bag)]).
data(faded_cyan_bag,[record(4,mirrored_tan_bag)]).
data(mirrored_coral_bag,[record(4,pale_gold_bag),record(5,wavy_gold_bag)]).
data(muted_beige_bag,[record(4,faded_crimson_bag)]).
data(plaid_tan_bag,[record(5,bright_indigo_bag)]).
data(faded_gray_bag,[record(3,muted_salmon_bag),record(3,shiny_maroon_bag),record(3,faded_orange_bag)]).
data(vibrant_teal_bag,[record(1,drab_green_bag),record(1,pale_black_bag),record(5,faded_gold_bag)]).
data(dim_red_bag,[record(5,striped_olive_bag),record(4,drab_salmon_bag),record(4,dark_magenta_bag)]).
data(bright_teal_bag,[record(4,drab_green_bag),record(3,shiny_brown_bag),record(1,mirrored_crimson_bag),record(1,dotted_purple_bag)]).
data(wavy_silver_bag,[record(4,wavy_coral_bag),record(2,bright_aqua_bag)]).
data(drab_gray_bag,[record(4,drab_crimson_bag),record(4,faded_turquoise_bag),record(3,drab_lavender_bag),record(3,bright_bronze_bag)]).
data(vibrant_gold_bag,[record(2,muted_black_bag)]).
data(faded_brown_bag,[record(3,posh_fuchsia_bag),record(3,faded_tan_bag),record(1,dim_olive_bag)]).
data(pale_red_bag,[record(4,clear_orange_bag),record(3,striped_green_bag),record(5,striped_turquoise_bag)]).
data(faded_coral_bag,[record(3,dim_lime_bag),record(2,pale_indigo_bag),record(1,striped_red_bag)]).
data(muted_cyan_bag,[record(5,vibrant_aqua_bag),record(2,muted_violet_bag),record(3,clear_gold_bag),record(5,pale_maroon_bag)]).
data(bright_silver_bag,[record(3,posh_salmon_bag),record(1,posh_silver_bag),record(1,clear_teal_bag),record(3,dark_gold_bag)]).
data(vibrant_magenta_bag,[record(2,dark_violet_bag)]).
data(mirrored_magenta_bag,[record(4,drab_teal_bag),record(1,dark_purple_bag)]).
data(posh_orange_bag,[record(5,dim_teal_bag),record(5,clear_lavender_bag),record(2,dim_coral_bag),record(3,shiny_silver_bag)]).
data(dotted_gray_bag,[record(1,dim_blue_bag),record(3,striped_purple_bag),record(3,mirrored_coral_bag),record(5,clear_purple_bag)]).
data(dark_white_bag,[record(5,dim_teal_bag),record(5,dark_turquoise_bag),record(3,wavy_indigo_bag),record(5,muted_olive_bag)]).
data(posh_black_bag,[record(5,striped_purple_bag)]).
data(faded_teal_bag,[record(2,muted_beige_bag),record(4,dim_blue_bag),record(3,light_purple_bag)]).
data(light_maroon_bag,[record(5,dotted_lime_bag),record(3,mirrored_salmon_bag),record(2,dark_coral_bag),record(4,muted_violet_bag)]).
data(striped_violet_bag,[record(5,mirrored_turquoise_bag),record(1,light_green_bag),record(1,striped_tan_bag),record(4,faded_violet_bag)]).
data(dotted_red_bag,[record(4,bright_aqua_bag),record(2,dull_maroon_bag),record(3,plaid_fuchsia_bag),record(2,dim_green_bag)]).
data(shiny_salmon_bag,[record(4,pale_chartreuse_bag),record(1,muted_tomato_bag)]).
data(posh_beige_bag,[record(2,drab_silver_bag),record(2,dull_purple_bag),record(4,dotted_magenta_bag)]).
data(faded_magenta_bag,[record(4,bright_beige_bag),record(3,pale_purple_bag),record(2,posh_plum_bag)]).
data(striped_teal_bag,[record(2,light_tomato_bag)]).
data(shiny_beige_bag,[record(3,posh_turquoise_bag),record(4,drab_lavender_bag),record(3,dark_magenta_bag),record(5,dotted_teal_bag)]).
data(dull_violet_bag,[record(2,dull_teal_bag),record(4,shiny_fuchsia_bag),record(2,bright_coral_bag),record(1,pale_bronze_bag)]).
data(light_fuchsia_bag,[record(2,pale_crimson_bag),record(4,bright_blue_bag)]).
data(faded_tomato_bag,[record(4,bright_fuchsia_bag),record(3,posh_tan_bag),record(3,dark_blue_bag)]).
data(posh_tan_bag,[record(2,bright_aqua_bag),record(1,mirrored_purple_bag),record(2,clear_lavender_bag)]).
data(dim_cyan_bag,[record(2,dim_beige_bag),record(2,dotted_orange_bag),record(4,muted_orange_bag),record(3,light_plum_bag)]).
data(plaid_chartreuse_bag,[record(2,light_orange_bag),record(5,dim_fuchsia_bag),record(2,mirrored_gray_bag),record(4,mirrored_tan_bag)]).
data(drab_silver_bag,[record(2,dim_blue_bag),record(2,light_lavender_bag),record(3,wavy_tomato_bag)]).
data(dull_lavender_bag,[record(5,dull_magenta_bag),record(3,dotted_tomato_bag),record(5,faded_gold_bag),record(2,pale_tan_bag)]).
data(drab_cyan_bag,[record(3,pale_plum_bag)]).
data(faded_green_bag,[record(3,light_violet_bag),record(3,pale_maroon_bag)]).
data(plaid_red_bag,[record(1,clear_olive_bag)]).
data(drab_tomato_bag,[record(3,faded_yellow_bag),record(5,striped_fuchsia_bag),record(4,light_gold_bag),record(1,faded_bronze_bag)]).
data(dotted_black_bag,[record(5,vibrant_aqua_bag)]).
data(striped_fuchsia_bag,[record(1,muted_olive_bag),record(2,pale_black_bag),record(2,light_teal_bag)]).
data(light_coral_bag,[record(4,striped_fuchsia_bag)]).
data(posh_coral_bag,[record(5,faded_tan_bag)]).
data(faded_blue_bag,[record(3,dim_chartreuse_bag),record(5,bright_coral_bag)]).
data(plaid_green_bag,[record(5,striped_plum_bag),record(3,faded_turquoise_bag),record(5,bright_beige_bag)]).
data(dark_cyan_bag,[record(2,bright_turquoise_bag),record(4,plaid_plum_bag),record(1,shiny_green_bag)]).
data(posh_yellow_bag,[record(3,pale_yellow_bag),record(3,muted_purple_bag),record(1,light_magenta_bag),record(4,light_aqua_bag)]).
data(mirrored_turquoise_bag,[record(2,vibrant_gray_bag),record(4,drab_orange_bag)]).
data(faded_tan_bag,[record(2,drab_orange_bag)]).
data(posh_plum_bag,[record(1,light_gold_bag),record(4,posh_orange_bag)]).
data(muted_chartreuse_bag,[record(2,shiny_violet_bag),record(1,pale_plum_bag),record(1,dim_crimson_bag)]).
data(muted_white_bag,[record(5,pale_brown_bag),record(5,clear_lavender_bag),record(1,faded_bronze_bag)]).
data(pale_plum_bag,[record(5,dotted_violet_bag),record(5,mirrored_gray_bag)]).
data(plaid_tomato_bag,[record(4,vibrant_coral_bag),record(4,dim_aqua_bag)]).
data(vibrant_cyan_bag,[record(1,shiny_lavender_bag),record(3,faded_orange_bag),record(2,striped_fuchsia_bag)]).
data(shiny_silver_bag,[no_other_bags]).
data(vibrant_aqua_bag,[record(3,plaid_orange_bag),record(2,light_blue_bag)]).
data(dotted_purple_bag,[record(4,faded_gold_bag),record(4,clear_green_bag),record(1,mirrored_gray_bag)]).
data(light_chartreuse_bag,[record(1,bright_black_bag)]).
data(mirrored_aqua_bag,[record(4,drab_salmon_bag),record(2,striped_red_bag)]).
data(faded_lime_bag,[record(4,faded_gold_bag)]).
data(clear_indigo_bag,[record(3,dim_tomato_bag),record(1,light_purple_bag),record(3,dark_salmon_bag),record(5,posh_teal_bag)]).
data(wavy_violet_bag,[record(2,posh_turquoise_bag)]).
data(light_blue_bag,[record(1,vibrant_turquoise_bag),record(5,vibrant_salmon_bag),record(2,light_gold_bag)]).
data(clear_blue_bag,[record(4,bright_aqua_bag)]).
data(bright_coral_bag,[record(1,light_lavender_bag)]).
data(light_green_bag,[record(2,pale_silver_bag),record(3,light_lavender_bag),record(2,posh_silver_bag)]).
data(dark_lime_bag,[record(4,muted_crimson_bag),record(3,mirrored_teal_bag)]).
data(mirrored_red_bag,[record(5,dotted_cyan_bag),record(2,dull_brown_bag)]).
data(drab_purple_bag,[record(2,bright_salmon_bag),record(1,striped_plum_bag)]).
data(posh_red_bag,[record(5,drab_salmon_bag),record(5,posh_gold_bag),record(1,vibrant_crimson_bag),record(5,vibrant_yellow_bag)]).
data(clear_red_bag,[record(5,muted_white_bag),record(3,mirrored_gold_bag),record(1,plaid_blue_bag)]).
data(drab_fuchsia_bag,[record(4,drab_salmon_bag),record(5,dark_red_bag)]).
data(dark_tomato_bag,[record(4,plaid_orange_bag),record(1,dull_magenta_bag),record(5,striped_aqua_bag)]).
data(muted_crimson_bag,[record(2,vibrant_gray_bag)]).
data(muted_bronze_bag,[record(4,plaid_beige_bag),record(3,striped_red_bag),record(3,muted_olive_bag),record(5,dotted_indigo_bag)]).
data(faded_bronze_bag,[record(5,dim_teal_bag)]).
data(striped_maroon_bag,[record(5,bright_gold_bag),record(2,clear_brown_bag),record(3,vibrant_cyan_bag),record(4,dotted_coral_bag)]).
data(light_cyan_bag,[record(5,mirrored_turquoise_bag)]).
data(mirrored_cyan_bag,[record(1,muted_olive_bag),record(2,drab_salmon_bag),record(5,muted_indigo_bag)]).
data(plaid_lavender_bag,[record(1,light_teal_bag),record(4,dotted_indigo_bag),record(5,faded_green_bag),record(1,light_aqua_bag)]).
data(light_gray_bag,[record(5,mirrored_red_bag),record(1,plaid_magenta_bag),record(1,pale_black_bag),record(3,clear_blue_bag)]).
data(wavy_indigo_bag,[record(3,dim_teal_bag),record(2,shiny_gold_bag),record(4,dim_gold_bag)]).
data(bright_tomato_bag,[record(1,mirrored_gray_bag)]).
data(pale_blue_bag,[record(3,vibrant_teal_bag),record(3,muted_magenta_bag),record(1,mirrored_salmon_bag),record(4,striped_cyan_bag)]).
data(posh_bronze_bag,[record(1,bright_tomato_bag),record(2,bright_teal_bag),record(1,dark_magenta_bag),record(1,mirrored_silver_bag)]).
data(dotted_violet_bag,[record(4,shiny_silver_bag),record(5,drab_green_bag)]).
data(dark_black_bag,[record(3,vibrant_gray_bag),record(1,faded_bronze_bag),record(2,faded_gold_bag)]).
data(muted_gray_bag,[record(3,wavy_orange_bag),record(2,mirrored_tan_bag)]).
data(shiny_chartreuse_bag,[record(5,bright_turquoise_bag)]).
data(dull_red_bag,[record(5,wavy_olive_bag)]).
data(dark_orange_bag,[record(3,plaid_bronze_bag),record(1,dark_blue_bag),record(1,dim_gray_bag),record(4,pale_chartreuse_bag)]).
data(wavy_yellow_bag,[record(3,plaid_indigo_bag),record(3,dull_purple_bag)]).
data(drab_salmon_bag,[record(3,light_blue_bag),record(2,dull_brown_bag)]).
data(drab_beige_bag,[record(2,pale_turquoise_bag),record(5,light_gold_bag),record(4,bright_aqua_bag)]).
data(dull_olive_bag,[record(2,pale_chartreuse_bag),record(3,dull_cyan_bag),record(5,mirrored_teal_bag)]).
data(wavy_crimson_bag,[record(4,faded_orange_bag),record(5,bright_gray_bag)]).
data(muted_maroon_bag,[record(1,muted_salmon_bag)]).
data(mirrored_white_bag,[record(2,light_bronze_bag),record(3,clear_brown_bag),record(2,dark_turquoise_bag),record(2,dim_indigo_bag)]).
data(wavy_gray_bag,[record(1,light_lime_bag),record(1,faded_turquoise_bag),record(4,muted_teal_bag),record(2,dim_crimson_bag)]).
data(shiny_gray_bag,[record(4,dull_cyan_bag),record(2,clear_red_bag),record(5,dark_magenta_bag)]).
data(dull_orange_bag,[record(1,dull_indigo_bag)]).
data(drab_maroon_bag,[record(5,light_red_bag),record(1,pale_orange_bag)]).
data(shiny_blue_bag,[record(3,striped_magenta_bag),record(2,light_violet_bag)]).
data(pale_lavender_bag,[record(5,faded_tan_bag),record(4,light_tan_bag),record(1,striped_coral_bag)]).
data(wavy_magenta_bag,[record(4,dull_crimson_bag)]).
data(bright_maroon_bag,[record(5,shiny_salmon_bag)]).
data(bright_gray_bag,[record(5,light_blue_bag),record(3,faded_gold_bag),record(5,dull_tomato_bag),record(2,faded_silver_bag)]).
data(muted_aqua_bag,[record(4,mirrored_purple_bag),record(5,light_blue_bag)]).
data(dull_plum_bag,[record(3,shiny_purple_bag),record(3,dim_indigo_bag)]).
data(light_indigo_bag,[record(2,mirrored_bronze_bag),record(4,wavy_lime_bag)]).
data(shiny_crimson_bag,[record(4,dull_violet_bag)]).
data(dull_lime_bag,[record(1,mirrored_gray_bag),record(1,shiny_brown_bag),record(5,dark_fuchsia_bag),record(4,shiny_silver_bag)]).
data(drab_chartreuse_bag,[record(4,muted_purple_bag),record(5,bright_magenta_bag),record(4,dark_salmon_bag),record(3,pale_indigo_bag)]).
data(faded_aqua_bag,[record(1,dotted_white_bag),record(1,drab_olive_bag)]).
data(dotted_magenta_bag,[record(5,wavy_tomato_bag),record(2,striped_fuchsia_bag),record(3,dull_blue_bag),record(3,pale_yellow_bag)]).
data(bright_tan_bag,[record(1,dark_blue_bag),record(5,vibrant_turquoise_bag)]).
data(dotted_fuchsia_bag,[record(2,dull_silver_bag)]).
data(dotted_plum_bag,[record(1,wavy_coral_bag),record(3,vibrant_teal_bag),record(2,dim_bronze_bag),record(1,pale_salmon_bag)]).
data(clear_silver_bag,[record(1,faded_orange_bag)]).
data(faded_beige_bag,[record(4,mirrored_orange_bag),record(4,plaid_white_bag),record(1,muted_violet_bag)]).
data(bright_red_bag,[record(5,posh_fuchsia_bag),record(4,striped_cyan_bag)]).
data(faded_yellow_bag,[record(3,vibrant_turquoise_bag),record(5,bright_teal_bag),record(3,pale_white_bag)]).
data(light_red_bag,[record(4,shiny_bronze_bag),record(2,mirrored_gray_bag),record(5,dark_violet_bag)]).
data(dim_orange_bag,[record(3,dull_brown_bag),record(3,dim_turquoise_bag),record(3,bright_chartreuse_bag),record(1,dark_red_bag)]).
data(posh_salmon_bag,[record(2,faded_lavender_bag),record(1,faded_brown_bag)]).
data(shiny_white_bag,[record(5,clear_crimson_bag)]).
data(shiny_black_bag,[record(2,vibrant_coral_bag),record(2,wavy_indigo_bag),record(4,shiny_gold_bag),record(4,mirrored_tan_bag)]).
data(pale_turquoise_bag,[record(2,dim_olive_bag)]).
data(vibrant_maroon_bag,[record(3,striped_turquoise_bag),record(3,clear_magenta_bag),record(1,dark_fuchsia_bag),record(5,dark_brown_bag)]).
data(wavy_coral_bag,[record(5,vibrant_aqua_bag)]).
data(striped_green_bag,[record(3,light_magenta_bag),record(4,clear_magenta_bag),record(1,light_turquoise_bag)]).
data(dark_gray_bag,[record(3,dark_aqua_bag)]).
data(shiny_bronze_bag,[record(5,vibrant_turquoise_bag),record(1,faded_gold_bag),record(5,dark_fuchsia_bag),record(3,dotted_cyan_bag)]).
data(dull_teal_bag,[record(3,clear_cyan_bag),record(1,bright_chartreuse_bag),record(2,dull_gray_bag)]).
data(dark_fuchsia_bag,[record(1,dull_silver_bag),record(3,dim_gold_bag),record(1,clear_teal_bag),record(5,shiny_silver_bag)]).
data(posh_blue_bag,[record(4,drab_teal_bag)]).
data(drab_violet_bag,[record(3,dim_lavender_bag),record(1,vibrant_aqua_bag),record(4,muted_gray_bag)]).
data(wavy_white_bag,[record(1,dark_coral_bag),record(2,dotted_gray_bag)]).
data(muted_coral_bag,[record(1,vibrant_teal_bag),record(5,dim_tan_bag),record(4,light_bronze_bag)]).
data(dark_silver_bag,[record(5,shiny_purple_bag),record(2,posh_indigo_bag)]).
data(pale_bronze_bag,[record(3,striped_white_bag),record(1,pale_aqua_bag)]).
data(dotted_turquoise_bag,[record(2,dark_bronze_bag),record(2,mirrored_turquoise_bag),record(2,clear_yellow_bag),record(2,posh_orange_bag)]).
data(muted_turquoise_bag,[record(1,faded_blue_bag),record(1,dotted_crimson_bag)]).
data(faded_indigo_bag,[record(5,mirrored_blue_bag),record(3,striped_crimson_bag),record(3,light_green_bag)]).
data(bright_salmon_bag,[record(4,dim_gold_bag),record(1,mirrored_red_bag)]).
data(mirrored_violet_bag,[record(5,dull_tomato_bag),record(4,shiny_maroon_bag),record(3,dark_green_bag)]).
data(plaid_blue_bag,[record(1,bright_aqua_bag),record(1,light_gold_bag),record(4,mirrored_turquoise_bag),record(1,dim_gold_bag)]).
data(wavy_green_bag,[record(5,light_white_bag)]).
data(vibrant_gray_bag,[record(3,drab_green_bag),record(5,faded_bronze_bag)]).
data(vibrant_red_bag,[record(3,shiny_lavender_bag),record(5,light_indigo_bag),record(3,dotted_chartreuse_bag),record(3,bright_aqua_bag)]).
data(dotted_tomato_bag,[record(4,clear_green_bag),record(3,vibrant_gray_bag)]).
data(mirrored_teal_bag,[record(4,posh_orange_bag),record(3,shiny_gold_bag),record(4,clear_magenta_bag),record(4,dull_crimson_bag)]).
data(muted_brown_bag,[record(5,dotted_cyan_bag),record(1,pale_turquoise_bag),record(2,posh_olive_bag),record(2,light_black_bag)]).
data(wavy_beige_bag,[record(1,dull_tomato_bag)]).
data(pale_white_bag,[record(4,drab_orange_bag),record(3,dim_tomato_bag),record(2,clear_lavender_bag)]).
data(mirrored_purple_bag,[record(4,dim_lime_bag)]).
data(plaid_orange_bag,[record(1,faded_bronze_bag),record(3,dotted_violet_bag)]).
data(shiny_lime_bag,[record(4,light_green_bag),record(4,dim_orange_bag)]).
data(vibrant_tomato_bag,[record(4,pale_plum_bag),record(2,pale_maroon_bag)]).
data(bright_turquoise_bag,[record(2,dim_gold_bag),record(5,pale_maroon_bag),record(5,dull_tomato_bag),record(1,mirrored_beige_bag)]).
data(bright_lime_bag,[record(4,clear_beige_bag)]).
data(shiny_tan_bag,[record(4,bright_beige_bag)]).
data(mirrored_green_bag,[record(5,wavy_magenta_bag)]).
data(posh_green_bag,[record(1,plaid_aqua_bag)]).
data(vibrant_olive_bag,[record(4,striped_plum_bag)]).
data(vibrant_crimson_bag,[record(1,dim_lavender_bag),record(5,faded_bronze_bag),record(1,drab_green_bag),record(3,plaid_magenta_bag)]).
data(bright_gold_bag,[record(5,dark_purple_bag),record(4,dark_teal_bag),record(2,dark_white_bag),record(4,striped_white_bag)]).
data(wavy_chartreuse_bag,[record(1,wavy_gray_bag),record(2,faded_olive_bag)]).
data(muted_black_bag,[record(4,shiny_gold_bag),record(4,vibrant_turquoise_bag),record(5,shiny_magenta_bag)]).
data(pale_salmon_bag,[record(4,dotted_gray_bag),record(4,dim_turquoise_bag),record(2,clear_silver_bag)]).
data(drab_coral_bag,[record(3,shiny_lime_bag),record(4,light_green_bag),record(4,vibrant_olive_bag),record(5,bright_chartreuse_bag)]).
data(pale_green_bag,[record(2,clear_green_bag),record(5,shiny_green_bag)]).
data(striped_tan_bag,[no_other_bags]).
data(pale_silver_bag,[record(4,shiny_silver_bag),record(5,clear_gold_bag),record(1,dim_lime_bag)]).
data(pale_olive_bag,[record(3,muted_fuchsia_bag),record(3,shiny_tan_bag)]).
data(bright_cyan_bag,[record(4,clear_lavender_bag),record(4,drab_green_bag),record(1,striped_tan_bag)]).
data(drab_teal_bag,[record(3,drab_tan_bag),record(1,shiny_bronze_bag),record(1,light_green_bag)]).
data(muted_salmon_bag,[record(2,plaid_fuchsia_bag),record(1,shiny_purple_bag),record(4,wavy_silver_bag),record(2,dark_salmon_bag)]).
data(shiny_tomato_bag,[record(1,wavy_turquoise_bag),record(2,pale_gray_bag),record(5,bright_red_bag),record(1,dotted_aqua_bag)]).
data(clear_cyan_bag,[record(3,posh_tan_bag),record(4,dim_green_bag),record(3,plaid_blue_bag)]).
data(dim_lavender_bag,[record(5,light_coral_bag),record(5,dull_indigo_bag)]).
data(light_gold_bag,[record(4,faded_gold_bag),record(3,pale_plum_bag),record(2,clear_lavender_bag),record(1,dim_lime_bag)]).
data(muted_tan_bag,[record(2,plaid_gray_bag),record(3,muted_fuchsia_bag),record(4,posh_gray_bag),record(2,mirrored_brown_bag)]).
data(striped_olive_bag,[record(2,dim_lime_bag),record(3,dull_tomato_bag)]).
data(dim_green_bag,[record(4,light_blue_bag),record(5,dark_turquoise_bag)]).
data(pale_tan_bag,[record(1,light_indigo_bag),record(5,shiny_chartreuse_bag),record(5,dim_purple_bag),record(2,faded_gold_bag)]).
data(bright_orange_bag,[record(5,striped_white_bag),record(2,dim_lime_bag)]).
data(faded_orange_bag,[record(1,plaid_magenta_bag),record(2,striped_olive_bag)]).
data(posh_olive_bag,[record(2,bright_gold_bag),record(2,dull_tomato_bag)]).
data(dotted_silver_bag,[record(1,wavy_crimson_bag),record(5,light_green_bag),record(5,striped_plum_bag),record(5,shiny_silver_bag)]).
data(wavy_turquoise_bag,[record(5,striped_purple_bag),record(3,shiny_blue_bag),record(3,dotted_indigo_bag)]).
data(plaid_gray_bag,[record(1,posh_teal_bag)]).
data(dark_magenta_bag,[record(3,striped_olive_bag)]).
data(drab_magenta_bag,[record(2,drab_plum_bag)]).
data(bright_beige_bag,[record(1,clear_teal_bag),record(2,dotted_violet_bag),record(5,posh_lavender_bag),record(5,faded_bronze_bag)]).
data(dark_tan_bag,[record(2,posh_indigo_bag),record(3,light_green_bag)]).
data(muted_blue_bag,[record(1,shiny_fuchsia_bag),record(5,dark_white_bag),record(2,dull_brown_bag)]).
data(wavy_fuchsia_bag,[record(2,dotted_salmon_bag),record(3,striped_gray_bag),record(1,clear_silver_bag),record(3,shiny_maroon_bag)]).
data(light_plum_bag,[record(2,posh_chartreuse_bag),record(3,pale_orange_bag),record(1,striped_violet_bag)]).
data(dull_indigo_bag,[record(3,dim_coral_bag),record(5,bright_orange_bag),record(5,shiny_purple_bag),record(1,posh_fuchsia_bag)]).
data(light_olive_bag,[record(2,clear_plum_bag),record(2,dotted_indigo_bag),record(1,vibrant_maroon_bag),record(2,drab_crimson_bag)]).
data(pale_magenta_bag,[record(4,plaid_bronze_bag),record(4,muted_aqua_bag)]).
data(faded_white_bag,[record(1,shiny_salmon_bag),record(4,drab_fuchsia_bag),record(3,striped_cyan_bag),record(5,light_bronze_bag)]).
data(bright_bronze_bag,[record(2,bright_gold_bag)]).
data(dim_chartreuse_bag,[record(5,wavy_beige_bag),record(1,mirrored_silver_bag),record(5,pale_brown_bag),record(4,pale_silver_bag)]).
data(bright_black_bag,[record(1,light_teal_bag),record(3,shiny_bronze_bag),record(5,faded_beige_bag),record(3,striped_magenta_bag)]).
data(clear_coral_bag,[record(1,pale_gold_bag),record(3,dim_tomato_bag),record(3,dark_violet_bag),record(2,dim_purple_bag)]).
data(dark_indigo_bag,[record(1,vibrant_turquoise_bag)]).
data(mirrored_tomato_bag,[record(1,drab_yellow_bag),record(5,muted_olive_bag),record(3,wavy_black_bag),record(3,dotted_lavender_bag)]).
data(striped_plum_bag,[record(3,faded_bronze_bag),record(1,vibrant_gray_bag)]).
data(bright_purple_bag,[record(3,muted_gray_bag)]).
data(muted_gold_bag,[record(4,light_indigo_bag),record(4,bright_tomato_bag),record(3,striped_tomato_bag)]).
data(faded_lavender_bag,[record(5,wavy_indigo_bag)]).
data(striped_beige_bag,[record(2,striped_fuchsia_bag),record(5,mirrored_magenta_bag)]).
data(faded_fuchsia_bag,[record(1,mirrored_fuchsia_bag),record(1,posh_aqua_bag),record(4,clear_coral_bag),record(3,mirrored_magenta_bag)]).
data(bright_aqua_bag,[record(1,muted_white_bag)]).
data(pale_crimson_bag,[record(3,light_purple_bag)]).
data(wavy_aqua_bag,[record(2,shiny_purple_bag),record(1,posh_orange_bag),record(1,dark_red_bag),record(3,drab_lavender_bag)]).
data(posh_violet_bag,[record(4,wavy_teal_bag),record(4,dull_chartreuse_bag),record(4,wavy_salmon_bag)]).
data(light_salmon_bag,[record(4,mirrored_crimson_bag),record(1,striped_red_bag)]).
data(dim_beige_bag,[record(4,dim_turquoise_bag),record(4,drab_fuchsia_bag),record(2,vibrant_tomato_bag)]).
data(clear_yellow_bag,[record(5,mirrored_orange_bag),record(3,dark_teal_bag)]).
data(pale_fuchsia_bag,[record(1,mirrored_bronze_bag),record(3,posh_lavender_bag),record(2,shiny_lavender_bag)]).
data(posh_gold_bag,[record(1,bright_teal_bag),record(3,light_green_bag),record(4,muted_blue_bag),record(4,drab_green_bag)]).
data(striped_aqua_bag,[record(4,wavy_beige_bag),record(1,dotted_indigo_bag)]).
data(plaid_indigo_bag,[record(5,striped_green_bag),record(5,light_purple_bag)]).
data(muted_tomato_bag,[record(2,posh_tomato_bag),record(1,pale_coral_bag),record(3,muted_white_bag),record(5,dim_orange_bag)]).
data(mirrored_silver_bag,[record(1,faded_silver_bag),record(2,dull_bronze_bag),record(2,dim_red_bag),record(5,posh_brown_bag)]).
data(vibrant_silver_bag,[record(5,striped_olive_bag),record(2,clear_olive_bag),record(5,bright_coral_bag),record(1,plaid_fuchsia_bag)]).
data(dull_chartreuse_bag,[record(1,muted_aqua_bag)]).
data(dotted_green_bag,[record(4,vibrant_white_bag),record(1,dim_teal_bag)]).
data(plaid_cyan_bag,[record(4,faded_bronze_bag)]).
data(dark_crimson_bag,[record(5,shiny_purple_bag),record(1,dotted_brown_bag),record(4,clear_coral_bag),record(1,striped_lavender_bag)]).
data(muted_orange_bag,[record(2,drab_cyan_bag)]).
data(dark_salmon_bag,[record(1,pale_black_bag),record(2,dull_brown_bag)]).
data(striped_salmon_bag,[record(3,dim_aqua_bag),record(1,clear_purple_bag),record(3,muted_crimson_bag)]).
data(vibrant_lavender_bag,[record(3,posh_orange_bag),record(4,posh_indigo_bag),record(3,plaid_magenta_bag)]).
data(shiny_purple_bag,[record(2,dotted_violet_bag),record(5,striped_tan_bag),record(2,pale_plum_bag)]).
data(plaid_lime_bag,[record(4,wavy_salmon_bag),record(2,light_magenta_bag),record(5,striped_crimson_bag)]).
data(drab_blue_bag,[record(3,dull_orange_bag)]).
data(mirrored_salmon_bag,[record(4,pale_black_bag),record(3,posh_tan_bag),record(4,vibrant_violet_bag)]).
data(muted_red_bag,[record(3,light_coral_bag),record(5,muted_teal_bag),record(1,dark_blue_bag)]).
data(dotted_olive_bag,[record(2,clear_lime_bag),record(3,faded_bronze_bag),record(5,shiny_silver_bag),record(4,clear_magenta_bag)]).
data(shiny_cyan_bag,[record(3,light_green_bag),record(2,dull_maroon_bag),record(1,pale_aqua_bag),record(5,mirrored_gold_bag)]).
data(plaid_teal_bag,[record(1,dull_teal_bag),record(5,faded_white_bag),record(4,vibrant_purple_bag)]).
data(dull_silver_bag,[record(2,bright_cyan_bag),record(3,clear_green_bag)]).
data(dim_silver_bag,[record(5,dim_orange_bag)]).
data(dark_red_bag,[record(1,shiny_fuchsia_bag),record(5,drab_orange_bag),record(1,dull_lime_bag)]).
data(dull_gray_bag,[record(5,posh_tan_bag),record(5,mirrored_violet_bag),record(5,clear_gold_bag),record(3,striped_olive_bag)]).
data(mirrored_olive_bag,[record(3,mirrored_yellow_bag),record(4,striped_lavender_bag)]).
data(dull_gold_bag,[record(3,faded_beige_bag)]).
data(dim_olive_bag,[record(5,dull_maroon_bag),record(3,dull_beige_bag)]).
data(dark_blue_bag,[record(4,dim_lime_bag),record(4,muted_indigo_bag)]).
data(posh_silver_bag,[record(3,posh_lavender_bag),record(2,bright_beige_bag),record(5,dim_coral_bag)]).
data(dotted_indigo_bag,[record(2,pale_gray_bag),record(4,light_violet_bag)]).
data(plaid_turquoise_bag,[record(1,pale_purple_bag),record(1,pale_brown_bag)]).
data(striped_purple_bag,[record(2,shiny_brown_bag)]).
data(dull_turquoise_bag,[record(3,dull_teal_bag),record(3,dark_coral_bag),record(4,dull_silver_bag),record(4,faded_violet_bag)]).
data(plaid_olive_bag,[record(3,dim_green_bag),record(1,wavy_chartreuse_bag),record(5,pale_crimson_bag),record(5,mirrored_green_bag)]).
data(clear_tomato_bag,[record(1,posh_gray_bag),record(4,clear_teal_bag),record(2,drab_indigo_bag)]).
data(dull_tan_bag,[record(4,vibrant_brown_bag),record(3,drab_orange_bag),record(5,bright_maroon_bag)]).
data(dark_gold_bag,[record(3,light_teal_bag)]).
data(faded_olive_bag,[record(4,clear_gold_bag)]).
data(posh_fuchsia_bag,[record(2,dull_brown_bag),record(1,dull_silver_bag),record(3,mirrored_tan_bag),record(2,dim_coral_bag)]).
data(dull_purple_bag,[record(1,dim_turquoise_bag),record(3,plaid_coral_bag),record(5,striped_lime_bag)]).
data(bright_plum_bag,[record(3,pale_green_bag),record(2,pale_gray_bag)]).
data(faded_violet_bag,[record(2,plaid_white_bag)]).
data(striped_lime_bag,[record(2,striped_cyan_bag)]).
data(clear_lime_bag,[record(3,faded_orange_bag),record(1,posh_lavender_bag),record(3,dull_lime_bag)]).
data(drab_red_bag,[record(2,dim_gold_bag),record(4,dotted_violet_bag)]).
data(mirrored_orange_bag,[record(2,mirrored_gold_bag),record(1,dull_gray_bag)]).
data(drab_white_bag,[record(1,vibrant_silver_bag),record(4,bright_cyan_bag),record(5,shiny_red_bag)]).
data(wavy_red_bag,[record(4,plaid_fuchsia_bag),record(2,pale_maroon_bag),record(4,wavy_indigo_bag)]).
data(pale_gray_bag,[record(2,dim_gold_bag)]).
data(mirrored_blue_bag,[record(4,dull_purple_bag),record(4,dull_bronze_bag),record(5,faded_violet_bag)]).
data(pale_aqua_bag,[record(2,shiny_brown_bag),record(2,vibrant_coral_bag),record(3,dark_green_bag),record(5,bright_beige_bag)]).
data(plaid_violet_bag,[record(2,dim_tomato_bag),record(5,dim_teal_bag),record(4,drab_salmon_bag)]).
data(shiny_magenta_bag,[record(5,dull_beige_bag)]).
data(striped_magenta_bag,[record(2,drab_olive_bag),record(3,dim_chartreuse_bag),record(3,plaid_beige_bag),record(5,mirrored_crimson_bag)]).
data(faded_black_bag,[record(1,bright_coral_bag),record(1,mirrored_magenta_bag),record(1,pale_coral_bag),record(4,posh_bronze_bag)]).
data(plaid_yellow_bag,[record(2,vibrant_gray_bag),record(1,mirrored_cyan_bag),record(2,light_salmon_bag),record(1,light_gold_bag)]).
data(vibrant_brown_bag,[record(3,light_tomato_bag),record(1,dark_red_bag)]).
data(faded_salmon_bag,[record(2,mirrored_orange_bag)]).
data(light_beige_bag,[record(1,vibrant_violet_bag),record(4,dim_green_bag),record(2,bright_aqua_bag)]).
data(bright_magenta_bag,[record(4,mirrored_brown_bag),record(4,faded_white_bag)]).
data(clear_violet_bag,[record(5,mirrored_gold_bag),record(5,bright_lavender_bag),record(5,dim_red_bag)]).
data(striped_blue_bag,[record(3,clear_turquoise_bag)]).
data(mirrored_fuchsia_bag,[record(2,shiny_fuchsia_bag),record(5,faded_bronze_bag),record(3,dull_lime_bag),record(3,drab_purple_bag)]).
data(drab_lime_bag,[record(4,pale_yellow_bag),record(3,drab_salmon_bag),record(5,clear_beige_bag)]).
data(wavy_maroon_bag,[record(3,drab_cyan_bag),record(5,light_turquoise_bag)]).
data(striped_coral_bag,[record(4,dull_magenta_bag),record(5,posh_maroon_bag),record(3,shiny_red_bag)]).
data(wavy_lime_bag,[record(1,plaid_green_bag)]).
data(dim_maroon_bag,[record(4,faded_lime_bag),record(1,striped_olive_bag),record(4,dull_bronze_bag)]).
data(clear_orange_bag,[record(5,posh_bronze_bag),record(4,striped_tan_bag),record(4,mirrored_bronze_bag)]).
data(vibrant_plum_bag,[record(1,bright_white_bag),record(5,light_aqua_bag),record(4,mirrored_fuchsia_bag),record(2,vibrant_purple_bag)]).
data(drab_bronze_bag,[record(3,light_gray_bag),record(2,faded_orange_bag),record(4,pale_black_bag)]).
data(mirrored_brown_bag,[record(1,light_blue_bag),record(2,posh_olive_bag),record(5,vibrant_magenta_bag)]).
data(mirrored_gray_bag,[no_other_bags]).
data(dim_aqua_bag,[record(3,bright_tomato_bag)]).
data(clear_aqua_bag,[record(3,drab_indigo_bag),record(4,light_bronze_bag),record(5,drab_teal_bag)]).
data(dull_yellow_bag,[record(4,dim_magenta_bag)]).
data(shiny_indigo_bag,[record(4,wavy_red_bag),record(3,dim_salmon_bag),record(5,dull_brown_bag)]).
data(striped_crimson_bag,[record(1,light_green_bag),record(2,dull_blue_bag),record(5,dotted_olive_bag)]).
data(mirrored_yellow_bag,[record(4,dull_maroon_bag),record(4,mirrored_aqua_bag)]).
data(drab_aqua_bag,[record(1,drab_teal_bag),record(1,dull_gold_bag),record(4,dim_red_bag),record(3,dim_teal_bag)]).
data(clear_green_bag,[no_other_bags]).
data(plaid_bronze_bag,[record(2,vibrant_olive_bag),record(5,wavy_green_bag),record(4,muted_indigo_bag)]).
data(mirrored_black_bag,[record(2,striped_red_bag),record(2,drab_tomato_bag),record(4,shiny_maroon_bag),record(1,striped_gray_bag)]).
data(muted_purple_bag,[record(4,mirrored_maroon_bag),record(2,dull_white_bag),record(3,plaid_salmon_bag),record(1,faded_lime_bag)]).
data(drab_brown_bag,[record(3,vibrant_maroon_bag),record(5,posh_indigo_bag),record(2,light_silver_bag),record(5,bright_black_bag)]).
data(light_yellow_bag,[record(2,posh_olive_bag),record(4,light_turquoise_bag)]).
data(mirrored_indigo_bag,[record(5,pale_maroon_bag)]).
data(drab_black_bag,[record(3,mirrored_green_bag)]).
data(shiny_teal_bag,[record(2,dim_plum_bag),record(4,dotted_indigo_bag),record(1,mirrored_lime_bag),record(2,light_green_bag)]).
data(striped_chartreuse_bag,[record(2,dim_olive_bag),record(1,wavy_teal_bag)]).
data(drab_indigo_bag,[record(3,dull_blue_bag),record(3,bright_indigo_bag),record(1,dull_purple_bag)]).
data(faded_crimson_bag,[record(2,vibrant_gray_bag)]).
data(posh_white_bag,[record(2,shiny_violet_bag)]).
data(wavy_purple_bag,[record(3,drab_green_bag),record(5,muted_purple_bag),record(1,dull_teal_bag)]).
data(dotted_lime_bag,[record(2,drab_teal_bag)]).
data(dotted_orange_bag,[record(2,bright_salmon_bag)]).
data(posh_magenta_bag,[record(3,dotted_silver_bag)]).
data(striped_yellow_bag,[record(1,dull_chartreuse_bag),record(3,dark_maroon_bag),record(3,faded_orange_bag),record(3,shiny_salmon_bag)]).
data(dotted_yellow_bag,[record(1,dim_gold_bag),record(4,clear_brown_bag)]).
data(drab_orange_bag,[record(2,mirrored_crimson_bag),record(2,clear_lavender_bag),record(3,faded_bronze_bag),record(4,posh_lavender_bag)]).
data(dull_coral_bag,[record(5,dim_teal_bag),record(1,light_gold_bag),record(2,drab_lime_bag),record(3,faded_lavender_bag)]).
data(clear_gold_bag,[record(5,drab_green_bag),record(4,dim_coral_bag),record(3,dim_teal_bag)]).
data(dim_purple_bag,[record(4,bright_aqua_bag),record(5,posh_lavender_bag),record(5,vibrant_salmon_bag),record(3,pale_black_bag)]).
data(clear_salmon_bag,[record(1,vibrant_orange_bag),record(1,faded_orange_bag),record(5,dull_tomato_bag),record(3,mirrored_turquoise_bag)]).
data(clear_brown_bag,[record(5,faded_bronze_bag)]).
data(faded_maroon_bag,[record(2,dotted_blue_bag),record(4,plaid_fuchsia_bag),record(5,light_purple_bag),record(4,faded_purple_bag)]).
data(shiny_red_bag,[record(5,mirrored_crimson_bag),record(2,mirrored_cyan_bag),record(2,dark_bronze_bag),record(1,pale_plum_bag)]).
data(faded_red_bag,[record(5,dotted_yellow_bag),record(2,faded_bronze_bag)]).
data(dotted_gold_bag,[record(4,vibrant_coral_bag),record(1,clear_turquoise_bag)]).
data(wavy_olive_bag,[record(5,light_violet_bag),record(5,bright_white_bag),record(3,vibrant_chartreuse_bag),record(1,mirrored_silver_bag)]).
data(dark_brown_bag,[record(3,muted_blue_bag)]).
data(dim_salmon_bag,[record(1,dull_silver_bag),record(5,vibrant_purple_bag)]).
data(dark_chartreuse_bag,[record(3,dull_beige_bag),record(3,light_tan_bag),record(3,vibrant_cyan_bag)]).
data(clear_tan_bag,[record(2,vibrant_coral_bag)]).
data(clear_white_bag,[record(3,faded_bronze_bag)]).
data(dim_yellow_bag,[record(4,plaid_coral_bag),record(1,posh_tomato_bag),record(4,striped_turquoise_bag)]).
data(bright_indigo_bag,[record(4,dull_magenta_bag)]).
data(plaid_gold_bag,[record(2,dark_violet_bag),record(3,shiny_blue_bag),record(5,drab_indigo_bag),record(3,shiny_orange_bag)]).
data(dark_aqua_bag,[record(3,faded_indigo_bag),record(1,pale_brown_bag),record(5,muted_chartreuse_bag)]).
data(light_lime_bag,[record(5,muted_teal_bag)]).
data(dark_teal_bag,[record(1,dark_olive_bag),record(1,drab_lavender_bag),record(2,mirrored_purple_bag),record(1,pale_teal_bag)]).
data(faded_turquoise_bag,[record(1,posh_fuchsia_bag)]).
data(mirrored_plum_bag,[record(2,striped_chartreuse_bag)]).
data(clear_beige_bag,[record(1,plaid_blue_bag),record(5,faded_gold_bag),record(5,mirrored_crimson_bag),record(3,drab_lavender_bag)]).
data(dotted_salmon_bag,[record(1,clear_tan_bag),record(5,mirrored_gold_bag),record(5,faded_beige_bag)]).
data(posh_lavender_bag,[record(2,mirrored_gray_bag),record(3,clear_green_bag),record(5,dim_teal_bag)]).
data(bright_white_bag,[record(1,posh_gold_bag),record(5,mirrored_silver_bag)]).
data(dotted_cyan_bag,[record(5,mirrored_gray_bag),record(2,dull_silver_bag)]).
data(dim_tomato_bag,[record(5,dull_brown_bag)]).
data(dotted_brown_bag,[record(2,pale_turquoise_bag)]).
data(posh_cyan_bag,[record(5,dim_coral_bag)]).
data(muted_magenta_bag,[record(3,posh_olive_bag),record(2,dark_indigo_bag)]).
data(pale_purple_bag,[record(5,dotted_cyan_bag)]).
data(vibrant_salmon_bag,[record(3,dim_teal_bag),record(1,posh_lavender_bag),record(2,pale_purple_bag),record(4,plaid_magenta_bag)]).
data(mirrored_gold_bag,[record(5,dark_indigo_bag),record(4,mirrored_indigo_bag),record(4,dotted_cyan_bag)]).
data(striped_brown_bag,[record(5,posh_tomato_bag),record(5,posh_brown_bag),record(2,faded_turquoise_bag)]).
data(dark_bronze_bag,[record(5,bright_chartreuse_bag),record(4,striped_teal_bag),record(2,muted_black_bag),record(2,muted_olive_bag)]).
data(light_silver_bag,[record(1,plaid_cyan_bag),record(2,vibrant_coral_bag),record(1,muted_gray_bag),record(4,striped_purple_bag)]).
data(pale_violet_bag,[record(3,posh_teal_bag),record(1,dull_beige_bag),record(2,plaid_beige_bag)]).
data(clear_teal_bag,[no_other_bags]).
data(posh_lime_bag,[record(1,dark_coral_bag),record(5,bright_teal_bag),record(5,bright_cyan_bag),record(3,posh_fuchsia_bag)]).
data(light_crimson_bag,[record(4,dotted_beige_bag)]).
data(muted_lavender_bag,[record(1,light_fuchsia_bag),record(2,shiny_crimson_bag),record(2,drab_purple_bag)]).
data(plaid_crimson_bag,[record(4,mirrored_red_bag),record(1,posh_chartreuse_bag),record(2,muted_indigo_bag),record(1,plaid_lavender_bag)]).
data(light_magenta_bag,[record(3,drab_bronze_bag),record(1,dull_olive_bag)]).
data(bright_yellow_bag,[record(4,plaid_plum_bag)]).
data(vibrant_bronze_bag,[record(5,dotted_red_bag),record(4,wavy_silver_bag),record(4,dim_lime_bag)]).
data(bright_blue_bag,[record(1,clear_white_bag),record(1,wavy_aqua_bag)]).
data(dim_turquoise_bag,[record(5,pale_purple_bag),record(1,vibrant_magenta_bag),record(1,vibrant_turquoise_bag),record(3,shiny_brown_bag)]).
data(vibrant_chartreuse_bag,[record(4,muted_blue_bag),record(3,pale_indigo_bag),record(1,dark_black_bag),record(1,bright_tomato_bag)]).
data(light_tan_bag,[record(2,mirrored_beige_bag),record(5,dull_turquoise_bag)]).
data(wavy_salmon_bag,[record(5,dull_crimson_bag),record(2,bright_salmon_bag),record(3,muted_gold_bag)]).
data(mirrored_maroon_bag,[record(3,shiny_brown_bag),record(1,shiny_fuchsia_bag)]).
data(pale_teal_bag,[record(1,striped_purple_bag),record(3,drab_orange_bag),record(1,dull_silver_bag),record(1,dark_fuchsia_bag)]).
data(striped_tomato_bag,[record(2,dim_orange_bag)]).
data(light_teal_bag,[record(1,dull_tomato_bag),record(5,clear_gold_bag)]).
data(dark_olive_bag,[record(5,striped_white_bag),record(5,dim_red_bag)]).
data(wavy_orange_bag,[record(1,clear_green_bag)]).
data(plaid_brown_bag,[record(5,dull_olive_bag),record(3,wavy_gray_bag),record(1,dotted_violet_bag)]).
data(dim_white_bag,[record(3,clear_tan_bag),record(1,clear_yellow_bag),record(1,pale_crimson_bag)]).
data(vibrant_black_bag,[record(2,dim_fuchsia_bag),record(1,dull_lime_bag),record(3,faded_magenta_bag)]).
data(dotted_aqua_bag,[record(4,posh_tomato_bag),record(4,pale_plum_bag),record(1,posh_coral_bag)]).
data(striped_gold_bag,[record(5,dim_orange_bag),record(2,drab_green_bag),record(2,striped_red_bag),record(3,muted_violet_bag)]).
data(dim_gold_bag,[record(3,posh_lavender_bag),record(4,drab_green_bag),record(4,dim_teal_bag)]).
data(mirrored_bronze_bag,[record(4,pale_aqua_bag),record(4,faded_orange_bag)]).
data(mirrored_beige_bag,[record(3,wavy_gold_bag)]).
data(dotted_teal_bag,[record(3,dull_indigo_bag),record(4,mirrored_gold_bag)]).
data(dark_maroon_bag,[record(4,dark_turquoise_bag),record(5,mirrored_silver_bag),record(4,wavy_bronze_bag),record(4,clear_turquoise_bag)]).
data(wavy_teal_bag,[record(3,plaid_fuchsia_bag),record(2,drab_orange_bag),record(3,vibrant_teal_bag)]).
data(muted_lime_bag,[record(5,bright_blue_bag),record(3,light_salmon_bag)]).
data(plaid_plum_bag,[record(2,wavy_gold_bag),record(2,pale_aqua_bag)]).
data(striped_indigo_bag,[record(5,faded_black_bag)]).
data(clear_lavender_bag,[no_other_bags]).
data(dull_tomato_bag,[record(3,dim_lime_bag)]).
data(shiny_yellow_bag,[record(5,faded_coral_bag),record(2,striped_violet_bag),record(5,clear_orange_bag)]).
data(light_lavender_bag,[record(5,dull_maroon_bag)]).
data(pale_chartreuse_bag,[record(4,clear_green_bag)]).
data(posh_turquoise_bag,[record(2,striped_olive_bag),record(5,bright_chartreuse_bag)]).
data(bright_lavender_bag,[record(4,dark_white_bag),record(5,wavy_coral_bag)]).
data(shiny_lavender_bag,[record(2,wavy_lime_bag),record(2,wavy_bronze_bag)]).
data(light_black_bag,[record(4,pale_black_bag),record(4,pale_purple_bag),record(5,drab_lavender_bag)]).
data(plaid_maroon_bag,[record(1,clear_teal_bag),record(3,clear_lavender_bag),record(1,dim_chartreuse_bag),record(2,vibrant_teal_bag)]).
data(striped_cyan_bag,[record(4,posh_fuchsia_bag),record(4,faded_violet_bag)]).
data(striped_lavender_bag,[record(4,pale_yellow_bag)]).
data(posh_purple_bag,[record(4,light_tomato_bag),record(4,muted_crimson_bag)]).
data(dim_crimson_bag,[record(5,wavy_aqua_bag),record(2,pale_maroon_bag),record(4,faded_bronze_bag)]).
data(muted_fuchsia_bag,[record(2,striped_gray_bag),record(4,posh_gray_bag),record(5,clear_white_bag),record(5,dotted_orange_bag)]).
data(drab_turquoise_bag,[record(2,bright_indigo_bag)]).
data(vibrant_purple_bag,[record(3,mirrored_bronze_bag)]).
data(bright_olive_bag,[record(4,light_bronze_bag)]).
data(shiny_plum_bag,[record(1,muted_indigo_bag),record(2,light_lime_bag),record(4,clear_coral_bag),record(2,dim_lavender_bag)]).
data(dotted_beige_bag,[record(1,plaid_plum_bag),record(3,dark_coral_bag),record(2,wavy_indigo_bag)]).
data(striped_black_bag,[record(3,muted_gold_bag)]).
data(shiny_orange_bag,[record(2,faded_blue_bag),record(3,shiny_green_bag)]).
data(shiny_coral_bag,[record(1,posh_orange_bag),record(4,striped_red_bag),record(4,muted_yellow_bag),record(2,dull_lavender_bag)]).
data(vibrant_yellow_bag,[record(2,dull_fuchsia_bag),record(2,pale_coral_bag),record(1,muted_magenta_bag),record(3,drab_turquoise_bag)]).
data(shiny_gold_bag,[record(5,mirrored_crimson_bag),record(5,mirrored_tan_bag),record(5,drab_green_bag),record(5,shiny_silver_bag)]).
data(bright_violet_bag,[record(2,vibrant_white_bag),record(1,clear_green_bag),record(3,faded_yellow_bag)]).
data(mirrored_tan_bag,[record(2,dark_black_bag),record(4,clear_green_bag),record(2,bright_cyan_bag),record(4,faded_bronze_bag)]).
data(posh_indigo_bag,[record(4,pale_plum_bag),record(1,dark_brown_bag),record(4,dull_crimson_bag)]).
data(pale_indigo_bag,[record(3,posh_plum_bag)]).
data(drab_tan_bag,[record(1,light_gray_bag),record(5,drab_orange_bag)]).
data(muted_green_bag,[record(1,dotted_violet_bag),record(4,dotted_cyan_bag)]).
data(light_turquoise_bag,[record(2,posh_brown_bag)]).
data(dotted_blue_bag,[record(1,posh_purple_bag),record(4,plaid_gray_bag)]).
data(plaid_silver_bag,[record(3,wavy_maroon_bag),record(5,clear_black_bag),record(5,shiny_indigo_bag),record(2,striped_gold_bag)]).
data(dim_plum_bag,[record(3,dotted_fuchsia_bag),record(5,clear_yellow_bag),record(4,striped_red_bag)]).
data(dotted_chartreuse_bag,[record(1,clear_yellow_bag),record(1,dim_red_bag),record(4,dim_turquoise_bag),record(1,mirrored_orange_bag)]).
data(dim_blue_bag,[record(3,bright_turquoise_bag),record(3,light_blue_bag),record(2,wavy_red_bag)]).
data(faded_gold_bag,[record(3,mirrored_gray_bag),record(4,dotted_cyan_bag),record(5,mirrored_red_bag),record(4,shiny_silver_bag)]).
data(dull_fuchsia_bag,[record(1,plaid_cyan_bag),record(3,shiny_purple_bag)]).
data(dotted_coral_bag,[record(5,muted_aqua_bag),record(1,dark_orange_bag),record(3,bright_black_bag)]).
data(striped_bronze_bag,[record(5,mirrored_purple_bag),record(2,wavy_aqua_bag)]).
data(faded_silver_bag,[record(1,bright_salmon_bag),record(1,striped_olive_bag),record(3,vibrant_turquoise_bag)]).
data(vibrant_white_bag,[record(5,muted_crimson_bag),record(4,bright_orange_bag),record(2,dark_brown_bag)]).
data(shiny_fuchsia_bag,[record(2,dull_silver_bag),record(1,wavy_indigo_bag),record(5,shiny_gold_bag),record(2,bright_beige_bag)]).
data(drab_crimson_bag,[record(3,mirrored_purple_bag),record(2,clear_magenta_bag),record(3,light_indigo_bag),record(5,clear_brown_bag)]).
data(posh_aqua_bag,[record(2,dark_brown_bag),record(2,shiny_white_bag)]).
data(pale_tomato_bag,[record(5,posh_gray_bag),record(1,wavy_silver_bag),record(5,drab_crimson_bag),record(2,dotted_aqua_bag)]).
data(wavy_bronze_bag,[record(5,plaid_coral_bag)]).
data(dull_white_bag,[record(4,shiny_magenta_bag),record(1,clear_olive_bag),record(5,posh_silver_bag),record(4,dark_blue_bag)]).
data(shiny_aqua_bag,[record(5,drab_green_bag),record(4,dark_maroon_bag),record(3,striped_turquoise_bag),record(4,pale_white_bag)]).
data(wavy_brown_bag,[record(1,faded_gold_bag),record(2,bright_aqua_bag),record(5,dotted_tan_bag),record(3,vibrant_crimson_bag)]).
data(clear_black_bag,[record(1,dull_orange_bag),record(5,posh_fuchsia_bag),record(2,mirrored_cyan_bag),record(5,shiny_gold_bag)]).
data(posh_tomato_bag,[record(4,pale_plum_bag)]).
data(vibrant_fuchsia_bag,[record(4,drab_olive_bag),record(1,drab_bronze_bag),record(4,dull_blue_bag)]).
data(mirrored_lavender_bag,[record(2,faded_cyan_bag),record(3,mirrored_bronze_bag),record(2,faded_tan_bag),record(5,clear_cyan_bag)]).
data(mirrored_lime_bag,[record(4,dull_gray_bag),record(4,plaid_beige_bag)]).
data(faded_chartreuse_bag,[record(3,light_coral_bag)]).
data(dim_brown_bag,[record(3,pale_yellow_bag),record(4,striped_lime_bag)]).
data(pale_gold_bag,[record(3,striped_plum_bag)]).
data(mirrored_chartreuse_bag,[record(2,striped_salmon_bag),record(4,shiny_teal_bag),record(4,wavy_gold_bag),record(4,light_magenta_bag)]).
data(plaid_white_bag,[record(5,faded_orange_bag),record(4,dull_tomato_bag),record(1,vibrant_olive_bag)]).
data(clear_crimson_bag,[record(5,posh_maroon_bag),record(5,muted_white_bag),record(2,dim_fuchsia_bag),record(4,pale_maroon_bag)]).
data(wavy_tomato_bag,[record(3,dim_tan_bag),record(4,dim_orange_bag),record(1,mirrored_tan_bag),record(4,posh_indigo_bag)]).
data(dim_coral_bag,[no_other_bags]).
data(plaid_magenta_bag,[record(2,clear_gold_bag),record(1,posh_orange_bag)]).
data(wavy_gold_bag,[record(1,plaid_blue_bag),record(3,pale_purple_bag),record(3,pale_yellow_bag)]).
data(wavy_blue_bag,[record(2,light_white_bag),record(5,pale_magenta_bag),record(1,plaid_lime_bag),record(5,faded_cyan_bag)]).
data(pale_yellow_bag,[record(2,vibrant_gray_bag)]).
data(clear_chartreuse_bag,[record(1,light_gray_bag),record(1,dark_tomato_bag)]).
data(drab_lavender_bag,[record(4,vibrant_salmon_bag)]).
data(dark_turquoise_bag,[record(5,pale_plum_bag)]).
data(vibrant_tan_bag,[record(5,plaid_aqua_bag)]).
data(vibrant_green_bag,[record(4,vibrant_red_bag),record(3,vibrant_tomato_bag)]).
data(plaid_aqua_bag,[record(5,wavy_silver_bag),record(5,faded_silver_bag)]).
data(pale_brown_bag,[record(1,dark_fuchsia_bag),record(3,drab_green_bag),record(5,bright_cyan_bag)]).
data(drab_olive_bag,[record(1,dull_maroon_bag),record(4,dark_maroon_bag)]).
data(wavy_cyan_bag,[record(2,muted_blue_bag),record(4,clear_beige_bag)]).
data(dotted_white_bag,[record(5,dull_orange_bag)]).
data(shiny_green_bag,[record(2,vibrant_gray_bag),record(3,vibrant_tomato_bag),record(2,dark_violet_bag)]).
data(bright_fuchsia_bag,[record(2,vibrant_chartreuse_bag),record(2,dim_orange_bag),record(4,clear_orange_bag),record(5,posh_fuchsia_bag)]).
data(clear_purple_bag,[record(2,dim_gray_bag),record(1,shiny_tan_bag)]).
data(dotted_lavender_bag,[record(3,posh_gray_bag),record(4,dull_beige_bag),record(5,plaid_beige_bag),record(1,dull_teal_bag)]).
data(dull_salmon_bag,[record(2,muted_magenta_bag),record(4,muted_purple_bag),record(2,light_teal_bag),record(4,vibrant_cyan_bag)]).
data(dark_green_bag,[record(3,clear_lavender_bag),record(5,shiny_silver_bag)]).
data(dull_maroon_bag,[record(2,dark_fuchsia_bag),record(3,mirrored_red_bag),record(3,mirrored_gray_bag),record(5,dim_lime_bag)]).
data(clear_bronze_bag,[record(2,dull_turquoise_bag),record(4,dim_olive_bag),record(3,wavy_violet_bag),record(5,dotted_bronze_bag)]).
data(muted_silver_bag,[record(1,clear_green_bag),record(4,shiny_tan_bag)]).
data(dark_lavender_bag,[record(5,dim_gray_bag),record(4,dark_teal_bag)]).
data(light_violet_bag,[record(2,light_blue_bag),record(4,clear_lavender_bag),record(4,dim_teal_bag)]).
data(vibrant_violet_bag,[record(4,posh_plum_bag),record(5,dark_fuchsia_bag)]).
data(posh_teal_bag,[record(2,pale_indigo_bag),record(5,plaid_fuchsia_bag),record(3,muted_gray_bag)]).
data(posh_crimson_bag,[record(5,bright_gold_bag)]).
data(dark_yellow_bag,[record(4,muted_gold_bag),record(2,dull_aqua_bag)]).
data(drab_gold_bag,[record(4,dark_maroon_bag),record(1,dim_turquoise_bag),record(4,mirrored_cyan_bag)]).
data(dotted_tan_bag,[record(5,plaid_turquoise_bag),record(2,shiny_aqua_bag)]).
data(vibrant_indigo_bag,[record(1,faded_plum_bag),record(5,dark_purple_bag),record(4,drab_maroon_bag),record(3,dull_teal_bag)]).
data(muted_olive_bag,[record(3,dull_bronze_bag),record(3,drab_salmon_bag),record(1,plaid_magenta_bag),record(3,mirrored_purple_bag)]).
data(plaid_purple_bag,[record(1,plaid_turquoise_bag),record(1,muted_olive_bag),record(1,shiny_crimson_bag)]).
data(dim_lime_bag,[record(5,mirrored_gray_bag),record(3,plaid_magenta_bag),record(5,dark_fuchsia_bag),record(2,bright_beige_bag)]).
data(muted_violet_bag,[record(3,bright_aqua_bag),record(2,pale_brown_bag),record(3,dark_fuchsia_bag)]).
data(dark_beige_bag,[record(3,vibrant_fuchsia_bag),record(2,shiny_white_bag)]).
data(dim_gray_bag,[record(3,mirrored_violet_bag),record(1,plaid_orange_bag),record(4,vibrant_olive_bag),record(5,pale_white_bag)]).
data(pale_cyan_bag,[record(4,dark_red_bag),record(2,mirrored_beige_bag),record(5,shiny_purple_bag),record(3,dark_fuchsia_bag)]).
data(dim_indigo_bag,[record(2,faded_blue_bag),record(5,muted_bronze_bag)]).
data(shiny_brown_bag,[record(4,vibrant_salmon_bag),record(3,drab_orange_bag)]).
data(dull_black_bag,[record(5,shiny_cyan_bag),record(5,dark_purple_bag)]).
data(light_white_bag,[record(2,mirrored_beige_bag),record(2,faded_turquoise_bag)]).
data(dim_fuchsia_bag,[record(4,drab_salmon_bag),record(5,striped_gray_bag),record(2,light_gray_bag)]).
data(striped_gray_bag,[record(5,plaid_white_bag),record(5,mirrored_purple_bag),record(2,vibrant_aqua_bag),record(4,muted_indigo_bag)]).
data(wavy_lavender_bag,[record(3,dotted_cyan_bag),record(3,bright_chartreuse_bag),record(5,plaid_black_bag),record(3,dotted_gold_bag)]).
data(dull_blue_bag,[record(2,vibrant_olive_bag)]).
data(dark_violet_bag,[record(4,muted_white_bag),record(4,dim_lime_bag)]).
data(shiny_maroon_bag,[record(3,dotted_violet_bag),record(5,shiny_brown_bag),record(2,light_blue_bag)]).
data(drab_yellow_bag,[record(2,shiny_fuchsia_bag)]).
data(clear_fuchsia_bag,[record(5,wavy_gray_bag),record(4,wavy_white_bag),record(4,drab_gray_bag),record(4,bright_indigo_bag)]).
data(plaid_coral_bag,[record(3,dull_lime_bag),record(2,vibrant_olive_bag),record(4,shiny_gold_bag)]).
data(dull_beige_bag,[record(4,dull_blue_bag),record(2,pale_black_bag),record(5,dim_coral_bag)]).
data(plaid_salmon_bag,[record(1,bright_coral_bag),record(2,bright_tomato_bag),record(4,dim_tan_bag),record(4,shiny_purple_bag)]).
data(dim_bronze_bag,[record(4,posh_teal_bag),record(1,pale_salmon_bag)]).
data(dull_magenta_bag,[record(3,dull_lime_bag),record(2,light_gold_bag),record(2,striped_purple_bag)]).
data(plaid_fuchsia_bag,[record(5,dim_lime_bag),record(5,bright_cyan_bag),record(2,faded_silver_bag),record(1,posh_fuchsia_bag)]).
data(dark_plum_bag,[record(2,plaid_green_bag)]).
data(striped_silver_bag,[record(5,clear_silver_bag),record(2,dotted_orange_bag),record(5,striped_fuchsia_bag),record(4,posh_bronze_bag)]).
data(bright_green_bag,[record(4,bright_white_bag),record(4,mirrored_lavender_bag),record(2,shiny_blue_bag)]).
data(wavy_plum_bag,[record(4,light_turquoise_bag),record(4,shiny_violet_bag),record(5,dim_blue_bag)]).
data(bright_chartreuse_bag,[record(5,dim_gold_bag)]).
data(dotted_crimson_bag,[record(4,wavy_beige_bag)]).
data(dull_bronze_bag,[record(2,muted_white_bag),record(2,faded_orange_bag),record(1,plaid_blue_bag)]).
data(dull_crimson_bag,[record(5,pale_black_bag),record(5,dim_lime_bag),record(5,clear_lavender_bag),record(4,faded_orange_bag)]).
data(striped_red_bag,[record(3,shiny_maroon_bag),record(5,muted_yellow_bag),record(2,faded_lavender_bag),record(2,dark_olive_bag)]).
data(clear_magenta_bag,[record(4,dark_coral_bag)]).
data(plaid_beige_bag,[record(4,vibrant_purple_bag),record(5,drab_salmon_bag),record(2,clear_white_bag),record(5,dull_olive_bag)]).
data(dotted_bronze_bag,[record(5,dull_tomato_bag),record(5,clear_lime_bag),record(2,clear_gold_bag),record(5,mirrored_indigo_bag)]).
data(pale_black_bag,[record(3,faded_bronze_bag),record(3,dotted_violet_bag)]).
data(faded_purple_bag,[record(1,light_fuchsia_bag),record(4,dull_violet_bag)]).
data(clear_plum_bag,[record(2,vibrant_gray_bag),record(4,striped_tan_bag)]).
data(wavy_black_bag,[record(5,mirrored_turquoise_bag)]).
data(dark_coral_bag,[record(5,faded_violet_bag)]).
data(pale_orange_bag,[record(3,mirrored_red_bag),record(4,clear_olive_bag)]).
