data(posh_brown_bag,[dim_coral_bag,plaid_blue_bag,faded_bronze_bag,light_black_bag]).
data(vibrant_lime_bag,[dull_lavender_bag,dim_crimson_bag,mirrored_lavender_bag,muted_cyan_bag]).
data(clear_olive_bag,[wavy_gold_bag,dim_lime_bag,dull_tomato_bag,dark_turquoise_bag]).
data(dark_purple_bag,[striped_tan_bag,bright_cyan_bag,dark_indigo_bag]).
data(posh_maroon_bag,[bright_salmon_bag]).
data(dim_violet_bag,[pale_violet_bag,bright_gold_bag]).
data(clear_gray_bag,[bright_gray_bag]).
data(light_brown_bag,[light_aqua_bag,vibrant_yellow_bag,posh_green_bag]).
data(muted_yellow_bag,[drab_bronze_bag,dull_gray_bag,vibrant_olive_bag]).
data(striped_orange_bag,[mirrored_brown_bag,plaid_olive_bag]).
data(striped_turquoise_bag,[muted_indigo_bag]).
data(mirrored_crimson_bag,[no_other_bag]).
data(muted_teal_bag,[striped_purple_bag]).
data(light_purple_bag,[dim_coral_bag,striped_teal_bag,dim_teal_bag,clear_gold_bag]).
data(shiny_olive_bag,[muted_cyan_bag,wavy_white_bag,light_chartreuse_bag,mirrored_indigo_bag]).
data(dim_black_bag,[wavy_lavender_bag,drab_blue_bag]).
data(pale_maroon_bag,[vibrant_olive_bag]).
data(dotted_maroon_bag,[faded_lime_bag,clear_turquoise_bag]).
data(light_aqua_bag,[dark_brown_bag,shiny_gold_bag]).
data(vibrant_beige_bag,[pale_cyan_bag,dotted_crimson_bag,vibrant_teal_bag]).
data(striped_white_bag,[shiny_gold_bag]).
data(light_orange_bag,[dim_coral_bag,vibrant_coral_bag]).
data(dull_green_bag,[plaid_green_bag]).
data(shiny_turquoise_bag,[striped_olive_bag,drab_cyan_bag,dim_lime_bag,muted_brown_bag]).
data(posh_chartreuse_bag,[mirrored_indigo_bag,light_black_bag,mirrored_bronze_bag,light_gold_bag]).
data(drab_green_bag,[no_other_bag]).
data(drab_plum_bag,[pale_blue_bag,dull_teal_bag,striped_violet_bag]).
data(muted_indigo_bag,[dark_turquoise_bag]).
data(pale_beige_bag,[wavy_gray_bag,faded_lime_bag,bright_beige_bag,plaid_violet_bag]).
data(vibrant_blue_bag,[drab_tan_bag,dull_tomato_bag]).
data(vibrant_turquoise_bag,[posh_lavender_bag]).
data(clear_maroon_bag,[shiny_brown_bag]).
data(bright_crimson_bag,[faded_indigo_bag,dull_teal_bag]).
data(wavy_tan_bag,[dotted_fuchsia_bag,muted_fuchsia_bag,light_white_bag]).
data(dim_teal_bag,[no_other_bag]).
data(faded_plum_bag,[faded_cyan_bag,dull_lime_bag,vibrant_cyan_bag]).
data(vibrant_orange_bag,[plaid_salmon_bag,mirrored_yellow_bag]).
data(posh_gray_bag,[dark_indigo_bag,light_blue_bag,light_red_bag,pale_aqua_bag]).
data(dull_aqua_bag,[dark_fuchsia_bag,faded_silver_bag]).
data(light_bronze_bag,[muted_indigo_bag]).
data(pale_coral_bag,[plaid_tomato_bag,faded_plum_bag,mirrored_turquoise_bag,posh_lavender_bag]).
data(pale_lime_bag,[dotted_gray_bag,mirrored_coral_bag,pale_silver_bag,mirrored_yellow_bag]).
data(shiny_violet_bag,[faded_orange_bag,muted_indigo_bag,muted_violet_bag]).
data(vibrant_coral_bag,[posh_fuchsia_bag,dim_coral_bag,faded_gold_bag,dotted_violet_bag]).
data(dim_magenta_bag,[pale_purple_bag,plaid_turquoise_bag,bright_lavender_bag]).
data(dull_brown_bag,[vibrant_turquoise_bag,faded_bronze_bag,striped_tan_bag,dim_gold_bag]).
data(bright_brown_bag,[dark_teal_bag,posh_indigo_bag,drab_fuchsia_bag]).
data(dim_tan_bag,[dark_magenta_bag,clear_blue_bag,vibrant_olive_bag]).
data(plaid_black_bag,[pale_indigo_bag,clear_gold_bag]).
data(muted_plum_bag,[faded_brown_bag,drab_orange_bag,dull_turquoise_bag]).
data(light_tomato_bag,[wavy_coral_bag,drab_green_bag,dull_crimson_bag]).
data(dull_cyan_bag,[clear_blue_bag,clear_yellow_bag]).
data(clear_turquoise_bag,[pale_black_bag,pale_brown_bag,bright_beige_bag]).
data(faded_cyan_bag,[mirrored_tan_bag]).
data(mirrored_coral_bag,[pale_gold_bag,wavy_gold_bag]).
data(muted_beige_bag,[faded_crimson_bag]).
data(plaid_tan_bag,[bright_indigo_bag]).
data(faded_gray_bag,[muted_salmon_bag,shiny_maroon_bag,faded_orange_bag]).
data(vibrant_teal_bag,[drab_green_bag,pale_black_bag,faded_gold_bag]).
data(dim_red_bag,[striped_olive_bag,drab_salmon_bag,dark_magenta_bag]).
data(bright_teal_bag,[drab_green_bag,shiny_brown_bag,mirrored_crimson_bag,dotted_purple_bag]).
data(wavy_silver_bag,[wavy_coral_bag,bright_aqua_bag]).
data(drab_gray_bag,[drab_crimson_bag,faded_turquoise_bag,drab_lavender_bag,bright_bronze_bag]).
data(vibrant_gold_bag,[muted_black_bag]).
data(faded_brown_bag,[posh_fuchsia_bag,faded_tan_bag,dim_olive_bag]).
data(pale_red_bag,[clear_orange_bag,striped_green_bag,striped_turquoise_bag]).
data(faded_coral_bag,[dim_lime_bag,pale_indigo_bag,striped_red_bag]).
data(muted_cyan_bag,[vibrant_aqua_bag,muted_violet_bag,clear_gold_bag,pale_maroon_bag]).
data(bright_silver_bag,[posh_salmon_bag,posh_silver_bag,clear_teal_bag,dark_gold_bag]).
data(vibrant_magenta_bag,[dark_violet_bag]).
data(mirrored_magenta_bag,[drab_teal_bag,dark_purple_bag]).
data(posh_orange_bag,[dim_teal_bag,clear_lavender_bag,dim_coral_bag,shiny_silver_bag]).
data(dotted_gray_bag,[dim_blue_bag,striped_purple_bag,mirrored_coral_bag,clear_purple_bag]).
data(dark_white_bag,[dim_teal_bag,dark_turquoise_bag,wavy_indigo_bag,muted_olive_bag]).
data(posh_black_bag,[striped_purple_bag]).
data(faded_teal_bag,[muted_beige_bag,dim_blue_bag,light_purple_bag]).
data(light_maroon_bag,[dotted_lime_bag,mirrored_salmon_bag,dark_coral_bag,muted_violet_bag]).
data(striped_violet_bag,[mirrored_turquoise_bag,light_green_bag,striped_tan_bag,faded_violet_bag]).
data(dotted_red_bag,[bright_aqua_bag,dull_maroon_bag,plaid_fuchsia_bag,dim_green_bag]).
data(shiny_salmon_bag,[pale_chartreuse_bag,muted_tomato_bag]).
data(posh_beige_bag,[drab_silver_bag,dull_purple_bag,dotted_magenta_bag]).
data(faded_magenta_bag,[bright_beige_bag,pale_purple_bag,posh_plum_bag]).
data(striped_teal_bag,[light_tomato_bag]).
data(shiny_beige_bag,[posh_turquoise_bag,drab_lavender_bag,dark_magenta_bag,dotted_teal_bag]).
data(dull_violet_bag,[dull_teal_bag,shiny_fuchsia_bag,bright_coral_bag,pale_bronze_bag]).
data(light_fuchsia_bag,[pale_crimson_bag,bright_blue_bag]).
data(faded_tomato_bag,[bright_fuchsia_bag,posh_tan_bag,dark_blue_bag]).
data(posh_tan_bag,[bright_aqua_bag,mirrored_purple_bag,clear_lavender_bag]).
data(dim_cyan_bag,[dim_beige_bag,dotted_orange_bag,muted_orange_bag,light_plum_bag]).
data(plaid_chartreuse_bag,[light_orange_bag,dim_fuchsia_bag,mirrored_gray_bag,mirrored_tan_bag]).
data(drab_silver_bag,[dim_blue_bag,light_lavender_bag,wavy_tomato_bag]).
data(dull_lavender_bag,[dull_magenta_bag,dotted_tomato_bag,faded_gold_bag,pale_tan_bag]).
data(drab_cyan_bag,[pale_plum_bag]).
data(faded_green_bag,[light_violet_bag,pale_maroon_bag]).
data(plaid_red_bag,[clear_olive_bag]).
data(drab_tomato_bag,[faded_yellow_bag,striped_fuchsia_bag,light_gold_bag,faded_bronze_bag]).
data(dotted_black_bag,[vibrant_aqua_bag]).
data(striped_fuchsia_bag,[muted_olive_bag,pale_black_bag,light_teal_bag]).
data(light_coral_bag,[striped_fuchsia_bag]).
data(posh_coral_bag,[faded_tan_bag]).
data(faded_blue_bag,[dim_chartreuse_bag,bright_coral_bag]).
data(plaid_green_bag,[striped_plum_bag,faded_turquoise_bag,bright_beige_bag]).
data(dark_cyan_bag,[bright_turquoise_bag,plaid_plum_bag,shiny_green_bag]).
data(posh_yellow_bag,[pale_yellow_bag,muted_purple_bag,light_magenta_bag,light_aqua_bag]).
data(mirrored_turquoise_bag,[vibrant_gray_bag,drab_orange_bag]).
data(faded_tan_bag,[drab_orange_bag]).
data(posh_plum_bag,[light_gold_bag,posh_orange_bag]).
data(muted_chartreuse_bag,[shiny_violet_bag,pale_plum_bag,dim_crimson_bag]).
data(muted_white_bag,[pale_brown_bag,clear_lavender_bag,faded_bronze_bag]).
data(pale_plum_bag,[dotted_violet_bag,mirrored_gray_bag]).
data(plaid_tomato_bag,[vibrant_coral_bag,dim_aqua_bag]).
data(vibrant_cyan_bag,[shiny_lavender_bag,faded_orange_bag,striped_fuchsia_bag]).
data(shiny_silver_bag,[no_other_bag]).
data(vibrant_aqua_bag,[plaid_orange_bag,light_blue_bag]).
data(dotted_purple_bag,[faded_gold_bag,clear_green_bag,mirrored_gray_bag]).
data(light_chartreuse_bag,[bright_black_bag]).
data(mirrored_aqua_bag,[drab_salmon_bag,striped_red_bag]).
data(faded_lime_bag,[faded_gold_bag]).
data(clear_indigo_bag,[dim_tomato_bag,light_purple_bag,dark_salmon_bag,posh_teal_bag]).
data(wavy_violet_bag,[posh_turquoise_bag]).
data(light_blue_bag,[vibrant_turquoise_bag,vibrant_salmon_bag,light_gold_bag]).
data(clear_blue_bag,[bright_aqua_bag]).
data(bright_coral_bag,[light_lavender_bag]).
data(light_green_bag,[pale_silver_bag,light_lavender_bag,posh_silver_bag]).
data(dark_lime_bag,[muted_crimson_bag,mirrored_teal_bag]).
data(mirrored_red_bag,[dotted_cyan_bag,dull_brown_bag]).
data(drab_purple_bag,[bright_salmon_bag,striped_plum_bag]).
data(posh_red_bag,[drab_salmon_bag,posh_gold_bag,vibrant_crimson_bag,vibrant_yellow_bag]).
data(clear_red_bag,[muted_white_bag,mirrored_gold_bag,plaid_blue_bag]).
data(drab_fuchsia_bag,[drab_salmon_bag,dark_red_bag]).
data(dark_tomato_bag,[plaid_orange_bag,dull_magenta_bag,striped_aqua_bag]).
data(muted_crimson_bag,[vibrant_gray_bag]).
data(muted_bronze_bag,[plaid_beige_bag,striped_red_bag,muted_olive_bag,dotted_indigo_bag]).
data(faded_bronze_bag,[dim_teal_bag]).
data(striped_maroon_bag,[bright_gold_bag,clear_brown_bag,vibrant_cyan_bag,dotted_coral_bag]).
data(light_cyan_bag,[mirrored_turquoise_bag]).
data(mirrored_cyan_bag,[muted_olive_bag,drab_salmon_bag,muted_indigo_bag]).
data(plaid_lavender_bag,[light_teal_bag,dotted_indigo_bag,faded_green_bag,light_aqua_bag]).
data(light_gray_bag,[mirrored_red_bag,plaid_magenta_bag,pale_black_bag,clear_blue_bag]).
data(wavy_indigo_bag,[dim_teal_bag,shiny_gold_bag,dim_gold_bag]).
data(bright_tomato_bag,[mirrored_gray_bag]).
data(pale_blue_bag,[vibrant_teal_bag,muted_magenta_bag,mirrored_salmon_bag,striped_cyan_bag]).
data(posh_bronze_bag,[bright_tomato_bag,bright_teal_bag,dark_magenta_bag,mirrored_silver_bag]).
data(dotted_violet_bag,[shiny_silver_bag,drab_green_bag]).
data(dark_black_bag,[vibrant_gray_bag,faded_bronze_bag,faded_gold_bag]).
data(muted_gray_bag,[wavy_orange_bag,mirrored_tan_bag]).
data(shiny_chartreuse_bag,[bright_turquoise_bag]).
data(dull_red_bag,[wavy_olive_bag]).
data(dark_orange_bag,[plaid_bronze_bag,dark_blue_bag,dim_gray_bag,pale_chartreuse_bag]).
data(wavy_yellow_bag,[plaid_indigo_bag,dull_purple_bag]).
data(drab_salmon_bag,[light_blue_bag,dull_brown_bag]).
data(drab_beige_bag,[pale_turquoise_bag,light_gold_bag,bright_aqua_bag]).
data(dull_olive_bag,[pale_chartreuse_bag,dull_cyan_bag,mirrored_teal_bag]).
data(wavy_crimson_bag,[faded_orange_bag,bright_gray_bag]).
data(muted_maroon_bag,[muted_salmon_bag]).
data(mirrored_white_bag,[light_bronze_bag,clear_brown_bag,dark_turquoise_bag,dim_indigo_bag]).
data(wavy_gray_bag,[light_lime_bag,faded_turquoise_bag,muted_teal_bag,dim_crimson_bag]).
data(shiny_gray_bag,[dull_cyan_bag,clear_red_bag,dark_magenta_bag]).
data(dull_orange_bag,[dull_indigo_bag]).
data(drab_maroon_bag,[light_red_bag,pale_orange_bag]).
data(shiny_blue_bag,[striped_magenta_bag,light_violet_bag]).
data(pale_lavender_bag,[faded_tan_bag,light_tan_bag,striped_coral_bag]).
data(wavy_magenta_bag,[dull_crimson_bag]).
data(bright_maroon_bag,[shiny_salmon_bag]).
data(bright_gray_bag,[light_blue_bag,faded_gold_bag,dull_tomato_bag,faded_silver_bag]).
data(muted_aqua_bag,[mirrored_purple_bag,light_blue_bag]).
data(dull_plum_bag,[shiny_purple_bag,dim_indigo_bag]).
data(light_indigo_bag,[mirrored_bronze_bag,wavy_lime_bag]).
data(shiny_crimson_bag,[dull_violet_bag]).
data(dull_lime_bag,[mirrored_gray_bag,shiny_brown_bag,dark_fuchsia_bag,shiny_silver_bag]).
data(drab_chartreuse_bag,[muted_purple_bag,bright_magenta_bag,dark_salmon_bag,pale_indigo_bag]).
data(faded_aqua_bag,[dotted_white_bag,drab_olive_bag]).
data(dotted_magenta_bag,[wavy_tomato_bag,striped_fuchsia_bag,dull_blue_bag,pale_yellow_bag]).
data(bright_tan_bag,[dark_blue_bag,vibrant_turquoise_bag]).
data(dotted_fuchsia_bag,[dull_silver_bag]).
data(dotted_plum_bag,[wavy_coral_bag,vibrant_teal_bag,dim_bronze_bag,pale_salmon_bag]).
data(clear_silver_bag,[faded_orange_bag]).
data(faded_beige_bag,[mirrored_orange_bag,plaid_white_bag,muted_violet_bag]).
data(bright_red_bag,[posh_fuchsia_bag,striped_cyan_bag]).
data(faded_yellow_bag,[vibrant_turquoise_bag,bright_teal_bag,pale_white_bag]).
data(light_red_bag,[shiny_bronze_bag,mirrored_gray_bag,dark_violet_bag]).
data(dim_orange_bag,[dull_brown_bag,dim_turquoise_bag,bright_chartreuse_bag,dark_red_bag]).
data(posh_salmon_bag,[faded_lavender_bag,faded_brown_bag]).
data(shiny_white_bag,[clear_crimson_bag]).
data(shiny_black_bag,[vibrant_coral_bag,wavy_indigo_bag,shiny_gold_bag,mirrored_tan_bag]).
data(pale_turquoise_bag,[dim_olive_bag]).
data(vibrant_maroon_bag,[striped_turquoise_bag,clear_magenta_bag,dark_fuchsia_bag,dark_brown_bag]).
data(wavy_coral_bag,[vibrant_aqua_bag]).
data(striped_green_bag,[light_magenta_bag,clear_magenta_bag,light_turquoise_bag]).
data(dark_gray_bag,[dark_aqua_bag]).
data(shiny_bronze_bag,[vibrant_turquoise_bag,faded_gold_bag,dark_fuchsia_bag,dotted_cyan_bag]).
data(dull_teal_bag,[clear_cyan_bag,bright_chartreuse_bag,dull_gray_bag]).
data(dark_fuchsia_bag,[dull_silver_bag,dim_gold_bag,clear_teal_bag,shiny_silver_bag]).
data(posh_blue_bag,[drab_teal_bag]).
data(drab_violet_bag,[dim_lavender_bag,vibrant_aqua_bag,muted_gray_bag]).
data(wavy_white_bag,[dark_coral_bag,dotted_gray_bag]).
data(muted_coral_bag,[vibrant_teal_bag,dim_tan_bag,light_bronze_bag]).
data(dark_silver_bag,[shiny_purple_bag,posh_indigo_bag]).
data(pale_bronze_bag,[striped_white_bag,pale_aqua_bag]).
data(dotted_turquoise_bag,[dark_bronze_bag,mirrored_turquoise_bag,clear_yellow_bag,posh_orange_bag]).
data(muted_turquoise_bag,[faded_blue_bag,dotted_crimson_bag]).
data(faded_indigo_bag,[mirrored_blue_bag,striped_crimson_bag,light_green_bag]).
data(bright_salmon_bag,[dim_gold_bag,mirrored_red_bag]).
data(mirrored_violet_bag,[dull_tomato_bag,shiny_maroon_bag,dark_green_bag]).
data(plaid_blue_bag,[bright_aqua_bag,light_gold_bag,mirrored_turquoise_bag,dim_gold_bag]).
data(wavy_green_bag,[light_white_bag]).
data(vibrant_gray_bag,[drab_green_bag,faded_bronze_bag]).
data(vibrant_red_bag,[shiny_lavender_bag,light_indigo_bag,dotted_chartreuse_bag,bright_aqua_bag]).
data(dotted_tomato_bag,[clear_green_bag,vibrant_gray_bag]).
data(mirrored_teal_bag,[posh_orange_bag,shiny_gold_bag,clear_magenta_bag,dull_crimson_bag]).
data(muted_brown_bag,[dotted_cyan_bag,pale_turquoise_bag,posh_olive_bag,light_black_bag]).
data(wavy_beige_bag,[dull_tomato_bag]).
data(pale_white_bag,[drab_orange_bag,dim_tomato_bag,clear_lavender_bag]).
data(mirrored_purple_bag,[dim_lime_bag]).
data(plaid_orange_bag,[faded_bronze_bag,dotted_violet_bag]).
data(shiny_lime_bag,[light_green_bag,dim_orange_bag]).
data(vibrant_tomato_bag,[pale_plum_bag,pale_maroon_bag]).
data(bright_turquoise_bag,[dim_gold_bag,pale_maroon_bag,dull_tomato_bag,mirrored_beige_bag]).
data(bright_lime_bag,[clear_beige_bag]).
data(shiny_tan_bag,[bright_beige_bag]).
data(mirrored_green_bag,[wavy_magenta_bag]).
data(posh_green_bag,[plaid_aqua_bag]).
data(vibrant_olive_bag,[striped_plum_bag]).
data(vibrant_crimson_bag,[dim_lavender_bag,faded_bronze_bag,drab_green_bag,plaid_magenta_bag]).
data(bright_gold_bag,[dark_purple_bag,dark_teal_bag,dark_white_bag,striped_white_bag]).
data(wavy_chartreuse_bag,[wavy_gray_bag,faded_olive_bag]).
data(muted_black_bag,[shiny_gold_bag,vibrant_turquoise_bag,shiny_magenta_bag]).
data(pale_salmon_bag,[dotted_gray_bag,dim_turquoise_bag,clear_silver_bag]).
data(drab_coral_bag,[shiny_lime_bag,light_green_bag,vibrant_olive_bag,bright_chartreuse_bag]).
data(pale_green_bag,[clear_green_bag,shiny_green_bag]).
data(striped_tan_bag,[no_other_bag]).
data(pale_silver_bag,[shiny_silver_bag,clear_gold_bag,dim_lime_bag]).
data(pale_olive_bag,[muted_fuchsia_bag,shiny_tan_bag]).
data(bright_cyan_bag,[clear_lavender_bag,drab_green_bag,striped_tan_bag]).
data(drab_teal_bag,[drab_tan_bag,shiny_bronze_bag,light_green_bag]).
data(muted_salmon_bag,[plaid_fuchsia_bag,shiny_purple_bag,wavy_silver_bag,dark_salmon_bag]).
data(shiny_tomato_bag,[wavy_turquoise_bag,pale_gray_bag,bright_red_bag,dotted_aqua_bag]).
data(clear_cyan_bag,[posh_tan_bag,dim_green_bag,plaid_blue_bag]).
data(dim_lavender_bag,[light_coral_bag,dull_indigo_bag]).
data(light_gold_bag,[faded_gold_bag,pale_plum_bag,clear_lavender_bag,dim_lime_bag]).
data(muted_tan_bag,[plaid_gray_bag,muted_fuchsia_bag,posh_gray_bag,mirrored_brown_bag]).
data(striped_olive_bag,[dim_lime_bag,dull_tomato_bag]).
data(dim_green_bag,[light_blue_bag,dark_turquoise_bag]).
data(pale_tan_bag,[light_indigo_bag,shiny_chartreuse_bag,dim_purple_bag,faded_gold_bag]).
data(bright_orange_bag,[striped_white_bag,dim_lime_bag]).
data(faded_orange_bag,[plaid_magenta_bag,striped_olive_bag]).
data(posh_olive_bag,[bright_gold_bag,dull_tomato_bag]).
data(dotted_silver_bag,[wavy_crimson_bag,light_green_bag,striped_plum_bag,shiny_silver_bag]).
data(wavy_turquoise_bag,[striped_purple_bag,shiny_blue_bag,dotted_indigo_bag]).
data(plaid_gray_bag,[posh_teal_bag]).
data(dark_magenta_bag,[striped_olive_bag]).
data(drab_magenta_bag,[drab_plum_bag]).
data(bright_beige_bag,[clear_teal_bag,dotted_violet_bag,posh_lavender_bag,faded_bronze_bag]).
data(dark_tan_bag,[posh_indigo_bag,light_green_bag]).
data(muted_blue_bag,[shiny_fuchsia_bag,dark_white_bag,dull_brown_bag]).
data(wavy_fuchsia_bag,[dotted_salmon_bag,striped_gray_bag,clear_silver_bag,shiny_maroon_bag]).
data(light_plum_bag,[posh_chartreuse_bag,pale_orange_bag,striped_violet_bag]).
data(dull_indigo_bag,[dim_coral_bag,bright_orange_bag,shiny_purple_bag,posh_fuchsia_bag]).
data(light_olive_bag,[clear_plum_bag,dotted_indigo_bag,vibrant_maroon_bag,drab_crimson_bag]).
data(pale_magenta_bag,[plaid_bronze_bag,muted_aqua_bag]).
data(faded_white_bag,[shiny_salmon_bag,drab_fuchsia_bag,striped_cyan_bag,light_bronze_bag]).
data(bright_bronze_bag,[bright_gold_bag]).
data(dim_chartreuse_bag,[wavy_beige_bag,mirrored_silver_bag,pale_brown_bag,pale_silver_bag]).
data(bright_black_bag,[light_teal_bag,shiny_bronze_bag,faded_beige_bag,striped_magenta_bag]).
data(clear_coral_bag,[pale_gold_bag,dim_tomato_bag,dark_violet_bag,dim_purple_bag]).
data(dark_indigo_bag,[vibrant_turquoise_bag]).
data(mirrored_tomato_bag,[drab_yellow_bag,muted_olive_bag,wavy_black_bag,dotted_lavender_bag]).
data(striped_plum_bag,[faded_bronze_bag,vibrant_gray_bag]).
data(bright_purple_bag,[muted_gray_bag]).
data(muted_gold_bag,[light_indigo_bag,bright_tomato_bag,striped_tomato_bag]).
data(faded_lavender_bag,[wavy_indigo_bag]).
data(striped_beige_bag,[striped_fuchsia_bag,mirrored_magenta_bag]).
data(faded_fuchsia_bag,[mirrored_fuchsia_bag,posh_aqua_bag,clear_coral_bag,mirrored_magenta_bag]).
data(bright_aqua_bag,[muted_white_bag]).
data(pale_crimson_bag,[light_purple_bag]).
data(wavy_aqua_bag,[shiny_purple_bag,posh_orange_bag,dark_red_bag,drab_lavender_bag]).
data(posh_violet_bag,[wavy_teal_bag,dull_chartreuse_bag,wavy_salmon_bag]).
data(light_salmon_bag,[mirrored_crimson_bag,striped_red_bag]).
data(dim_beige_bag,[dim_turquoise_bag,drab_fuchsia_bag,vibrant_tomato_bag]).
data(clear_yellow_bag,[mirrored_orange_bag,dark_teal_bag]).
data(pale_fuchsia_bag,[mirrored_bronze_bag,posh_lavender_bag,shiny_lavender_bag]).
data(posh_gold_bag,[bright_teal_bag,light_green_bag,muted_blue_bag,drab_green_bag]).
data(striped_aqua_bag,[wavy_beige_bag,dotted_indigo_bag]).
data(plaid_indigo_bag,[striped_green_bag,light_purple_bag]).
data(muted_tomato_bag,[posh_tomato_bag,pale_coral_bag,muted_white_bag,dim_orange_bag]).
data(mirrored_silver_bag,[faded_silver_bag,dull_bronze_bag,dim_red_bag,posh_brown_bag]).
data(vibrant_silver_bag,[striped_olive_bag,clear_olive_bag,bright_coral_bag,plaid_fuchsia_bag]).
data(dull_chartreuse_bag,[muted_aqua_bag]).
data(dotted_green_bag,[vibrant_white_bag,dim_teal_bag]).
data(plaid_cyan_bag,[faded_bronze_bag]).
data(dark_crimson_bag,[shiny_purple_bag,dotted_brown_bag,clear_coral_bag,striped_lavender_bag]).
data(muted_orange_bag,[drab_cyan_bag]).
data(dark_salmon_bag,[pale_black_bag,dull_brown_bag]).
data(striped_salmon_bag,[dim_aqua_bag,clear_purple_bag,muted_crimson_bag]).
data(vibrant_lavender_bag,[posh_orange_bag,posh_indigo_bag,plaid_magenta_bag]).
data(shiny_purple_bag,[dotted_violet_bag,striped_tan_bag,pale_plum_bag]).
data(plaid_lime_bag,[wavy_salmon_bag,light_magenta_bag,striped_crimson_bag]).
data(drab_blue_bag,[dull_orange_bag]).
data(mirrored_salmon_bag,[pale_black_bag,posh_tan_bag,vibrant_violet_bag]).
data(muted_red_bag,[light_coral_bag,muted_teal_bag,dark_blue_bag]).
data(dotted_olive_bag,[clear_lime_bag,faded_bronze_bag,shiny_silver_bag,clear_magenta_bag]).
data(shiny_cyan_bag,[light_green_bag,dull_maroon_bag,pale_aqua_bag,mirrored_gold_bag]).
data(plaid_teal_bag,[dull_teal_bag,faded_white_bag,vibrant_purple_bag]).
data(dull_silver_bag,[bright_cyan_bag,clear_green_bag]).
data(dim_silver_bag,[dim_orange_bag]).
data(dark_red_bag,[shiny_fuchsia_bag,drab_orange_bag,dull_lime_bag]).
data(dull_gray_bag,[posh_tan_bag,mirrored_violet_bag,clear_gold_bag,striped_olive_bag]).
data(mirrored_olive_bag,[mirrored_yellow_bag,striped_lavender_bag]).
data(dull_gold_bag,[faded_beige_bag]).
data(dim_olive_bag,[dull_maroon_bag,dull_beige_bag]).
data(dark_blue_bag,[dim_lime_bag,muted_indigo_bag]).
data(posh_silver_bag,[posh_lavender_bag,bright_beige_bag,dim_coral_bag]).
data(dotted_indigo_bag,[pale_gray_bag,light_violet_bag]).
data(plaid_turquoise_bag,[pale_purple_bag,pale_brown_bag]).
data(striped_purple_bag,[shiny_brown_bag]).
data(dull_turquoise_bag,[dull_teal_bag,dark_coral_bag,dull_silver_bag,faded_violet_bag]).
data(plaid_olive_bag,[dim_green_bag,wavy_chartreuse_bag,pale_crimson_bag,mirrored_green_bag]).
data(clear_tomato_bag,[posh_gray_bag,clear_teal_bag,drab_indigo_bag]).
data(dull_tan_bag,[vibrant_brown_bag,drab_orange_bag,bright_maroon_bag]).
data(dark_gold_bag,[light_teal_bag]).
data(faded_olive_bag,[clear_gold_bag]).
data(posh_fuchsia_bag,[dull_brown_bag,dull_silver_bag,mirrored_tan_bag,dim_coral_bag]).
data(dull_purple_bag,[dim_turquoise_bag,plaid_coral_bag,striped_lime_bag]).
data(bright_plum_bag,[pale_green_bag,pale_gray_bag]).
data(faded_violet_bag,[plaid_white_bag]).
data(striped_lime_bag,[striped_cyan_bag]).
data(clear_lime_bag,[faded_orange_bag,posh_lavender_bag,dull_lime_bag]).
data(drab_red_bag,[dim_gold_bag,dotted_violet_bag]).
data(mirrored_orange_bag,[mirrored_gold_bag,dull_gray_bag]).
data(drab_white_bag,[vibrant_silver_bag,bright_cyan_bag,shiny_red_bag]).
data(wavy_red_bag,[plaid_fuchsia_bag,pale_maroon_bag,wavy_indigo_bag]).
data(pale_gray_bag,[dim_gold_bag]).
data(mirrored_blue_bag,[dull_purple_bag,dull_bronze_bag,faded_violet_bag]).
data(pale_aqua_bag,[shiny_brown_bag,vibrant_coral_bag,dark_green_bag,bright_beige_bag]).
data(plaid_violet_bag,[dim_tomato_bag,dim_teal_bag,drab_salmon_bag]).
data(shiny_magenta_bag,[dull_beige_bag]).
data(striped_magenta_bag,[drab_olive_bag,dim_chartreuse_bag,plaid_beige_bag,mirrored_crimson_bag]).
data(faded_black_bag,[bright_coral_bag,mirrored_magenta_bag,pale_coral_bag,posh_bronze_bag]).
data(plaid_yellow_bag,[vibrant_gray_bag,mirrored_cyan_bag,light_salmon_bag,light_gold_bag]).
data(vibrant_brown_bag,[light_tomato_bag,dark_red_bag]).
data(faded_salmon_bag,[mirrored_orange_bag]).
data(light_beige_bag,[vibrant_violet_bag,dim_green_bag,bright_aqua_bag]).
data(bright_magenta_bag,[mirrored_brown_bag,faded_white_bag]).
data(clear_violet_bag,[mirrored_gold_bag,bright_lavender_bag,dim_red_bag]).
data(striped_blue_bag,[clear_turquoise_bag]).
data(mirrored_fuchsia_bag,[shiny_fuchsia_bag,faded_bronze_bag,dull_lime_bag,drab_purple_bag]).
data(drab_lime_bag,[pale_yellow_bag,drab_salmon_bag,clear_beige_bag]).
data(wavy_maroon_bag,[drab_cyan_bag,light_turquoise_bag]).
data(striped_coral_bag,[dull_magenta_bag,posh_maroon_bag,shiny_red_bag]).
data(wavy_lime_bag,[plaid_green_bag]).
data(dim_maroon_bag,[faded_lime_bag,striped_olive_bag,dull_bronze_bag]).
data(clear_orange_bag,[posh_bronze_bag,striped_tan_bag,mirrored_bronze_bag]).
data(vibrant_plum_bag,[bright_white_bag,light_aqua_bag,mirrored_fuchsia_bag,vibrant_purple_bag]).
data(drab_bronze_bag,[light_gray_bag,faded_orange_bag,pale_black_bag]).
data(mirrored_brown_bag,[light_blue_bag,posh_olive_bag,vibrant_magenta_bag]).
data(mirrored_gray_bag,[no_other_bag]).
data(dim_aqua_bag,[bright_tomato_bag]).
data(clear_aqua_bag,[drab_indigo_bag,light_bronze_bag,drab_teal_bag]).
data(dull_yellow_bag,[dim_magenta_bag]).
data(shiny_indigo_bag,[wavy_red_bag,dim_salmon_bag,dull_brown_bag]).
data(striped_crimson_bag,[light_green_bag,dull_blue_bag,dotted_olive_bag]).
data(mirrored_yellow_bag,[dull_maroon_bag,mirrored_aqua_bag]).
data(drab_aqua_bag,[drab_teal_bag,dull_gold_bag,dim_red_bag,dim_teal_bag]).
data(clear_green_bag,[no_other_bag]).
data(plaid_bronze_bag,[vibrant_olive_bag,wavy_green_bag,muted_indigo_bag]).
data(mirrored_black_bag,[striped_red_bag,drab_tomato_bag,shiny_maroon_bag,striped_gray_bag]).
data(muted_purple_bag,[mirrored_maroon_bag,dull_white_bag,plaid_salmon_bag,faded_lime_bag]).
data(drab_brown_bag,[vibrant_maroon_bag,posh_indigo_bag,light_silver_bag,bright_black_bag]).
data(light_yellow_bag,[posh_olive_bag,light_turquoise_bag]).
data(mirrored_indigo_bag,[pale_maroon_bag]).
data(drab_black_bag,[mirrored_green_bag]).
data(shiny_teal_bag,[dim_plum_bag,dotted_indigo_bag,mirrored_lime_bag,light_green_bag]).
data(striped_chartreuse_bag,[dim_olive_bag,wavy_teal_bag]).
data(drab_indigo_bag,[dull_blue_bag,bright_indigo_bag,dull_purple_bag]).
data(faded_crimson_bag,[vibrant_gray_bag]).
data(posh_white_bag,[shiny_violet_bag]).
data(wavy_purple_bag,[drab_green_bag,muted_purple_bag,dull_teal_bag]).
data(dotted_lime_bag,[drab_teal_bag]).
data(dotted_orange_bag,[bright_salmon_bag]).
data(posh_magenta_bag,[dotted_silver_bag]).
data(striped_yellow_bag,[dull_chartreuse_bag,dark_maroon_bag,faded_orange_bag,shiny_salmon_bag]).
data(dotted_yellow_bag,[dim_gold_bag,clear_brown_bag]).
data(drab_orange_bag,[mirrored_crimson_bag,clear_lavender_bag,faded_bronze_bag,posh_lavender_bag]).
data(dull_coral_bag,[dim_teal_bag,light_gold_bag,drab_lime_bag,faded_lavender_bag]).
data(clear_gold_bag,[drab_green_bag,dim_coral_bag,dim_teal_bag]).
data(dim_purple_bag,[bright_aqua_bag,posh_lavender_bag,vibrant_salmon_bag,pale_black_bag]).
data(clear_salmon_bag,[vibrant_orange_bag,faded_orange_bag,dull_tomato_bag,mirrored_turquoise_bag]).
data(clear_brown_bag,[faded_bronze_bag]).
data(faded_maroon_bag,[dotted_blue_bag,plaid_fuchsia_bag,light_purple_bag,faded_purple_bag]).
data(shiny_red_bag,[mirrored_crimson_bag,mirrored_cyan_bag,dark_bronze_bag,pale_plum_bag]).
data(faded_red_bag,[dotted_yellow_bag,faded_bronze_bag]).
data(dotted_gold_bag,[vibrant_coral_bag,clear_turquoise_bag]).
data(wavy_olive_bag,[light_violet_bag,bright_white_bag,vibrant_chartreuse_bag,mirrored_silver_bag]).
data(dark_brown_bag,[muted_blue_bag]).
data(dim_salmon_bag,[dull_silver_bag,vibrant_purple_bag]).
data(dark_chartreuse_bag,[dull_beige_bag,light_tan_bag,vibrant_cyan_bag]).
data(clear_tan_bag,[vibrant_coral_bag]).
data(clear_white_bag,[faded_bronze_bag]).
data(dim_yellow_bag,[plaid_coral_bag,posh_tomato_bag,striped_turquoise_bag]).
data(bright_indigo_bag,[dull_magenta_bag]).
data(plaid_gold_bag,[dark_violet_bag,shiny_blue_bag,drab_indigo_bag,shiny_orange_bag]).
data(dark_aqua_bag,[faded_indigo_bag,pale_brown_bag,muted_chartreuse_bag]).
data(light_lime_bag,[muted_teal_bag]).
data(dark_teal_bag,[dark_olive_bag,drab_lavender_bag,mirrored_purple_bag,pale_teal_bag]).
data(faded_turquoise_bag,[posh_fuchsia_bag]).
data(mirrored_plum_bag,[striped_chartreuse_bag]).
data(clear_beige_bag,[plaid_blue_bag,faded_gold_bag,mirrored_crimson_bag,drab_lavender_bag]).
data(dotted_salmon_bag,[clear_tan_bag,mirrored_gold_bag,faded_beige_bag]).
data(posh_lavender_bag,[mirrored_gray_bag,clear_green_bag,dim_teal_bag]).
data(bright_white_bag,[posh_gold_bag,mirrored_silver_bag]).
data(dotted_cyan_bag,[mirrored_gray_bag,dull_silver_bag]).
data(dim_tomato_bag,[dull_brown_bag]).
data(dotted_brown_bag,[pale_turquoise_bag]).
data(posh_cyan_bag,[dim_coral_bag]).
data(muted_magenta_bag,[posh_olive_bag,dark_indigo_bag]).
data(pale_purple_bag,[dotted_cyan_bag]).
data(vibrant_salmon_bag,[dim_teal_bag,posh_lavender_bag,pale_purple_bag,plaid_magenta_bag]).
data(mirrored_gold_bag,[dark_indigo_bag,mirrored_indigo_bag,dotted_cyan_bag]).
data(striped_brown_bag,[posh_tomato_bag,posh_brown_bag,faded_turquoise_bag]).
data(dark_bronze_bag,[bright_chartreuse_bag,striped_teal_bag,muted_black_bag,muted_olive_bag]).
data(light_silver_bag,[plaid_cyan_bag,vibrant_coral_bag,muted_gray_bag,striped_purple_bag]).
data(pale_violet_bag,[posh_teal_bag,dull_beige_bag,plaid_beige_bag]).
data(clear_teal_bag,[no_other_bag]).
data(posh_lime_bag,[dark_coral_bag,bright_teal_bag,bright_cyan_bag,posh_fuchsia_bag]).
data(light_crimson_bag,[dotted_beige_bag]).
data(muted_lavender_bag,[light_fuchsia_bag,shiny_crimson_bag,drab_purple_bag]).
data(plaid_crimson_bag,[mirrored_red_bag,posh_chartreuse_bag,muted_indigo_bag,plaid_lavender_bag]).
data(light_magenta_bag,[drab_bronze_bag,dull_olive_bag]).
data(bright_yellow_bag,[plaid_plum_bag]).
data(vibrant_bronze_bag,[dotted_red_bag,wavy_silver_bag,dim_lime_bag]).
data(bright_blue_bag,[clear_white_bag,wavy_aqua_bag]).
data(dim_turquoise_bag,[pale_purple_bag,vibrant_magenta_bag,vibrant_turquoise_bag,shiny_brown_bag]).
data(vibrant_chartreuse_bag,[muted_blue_bag,pale_indigo_bag,dark_black_bag,bright_tomato_bag]).
data(light_tan_bag,[mirrored_beige_bag,dull_turquoise_bag]).
data(wavy_salmon_bag,[dull_crimson_bag,bright_salmon_bag,muted_gold_bag]).
data(mirrored_maroon_bag,[shiny_brown_bag,shiny_fuchsia_bag]).
data(pale_teal_bag,[striped_purple_bag,drab_orange_bag,dull_silver_bag,dark_fuchsia_bag]).
data(striped_tomato_bag,[dim_orange_bag]).
data(light_teal_bag,[dull_tomato_bag,clear_gold_bag]).
data(dark_olive_bag,[striped_white_bag,dim_red_bag]).
data(wavy_orange_bag,[clear_green_bag]).
data(plaid_brown_bag,[dull_olive_bag,wavy_gray_bag,dotted_violet_bag]).
data(dim_white_bag,[clear_tan_bag,clear_yellow_bag,pale_crimson_bag]).
data(vibrant_black_bag,[dim_fuchsia_bag,dull_lime_bag,faded_magenta_bag]).
data(dotted_aqua_bag,[posh_tomato_bag,pale_plum_bag,posh_coral_bag]).
data(striped_gold_bag,[dim_orange_bag,drab_green_bag,striped_red_bag,muted_violet_bag]).
data(dim_gold_bag,[posh_lavender_bag,drab_green_bag,dim_teal_bag]).
data(mirrored_bronze_bag,[pale_aqua_bag,faded_orange_bag]).
data(mirrored_beige_bag,[wavy_gold_bag]).
data(dotted_teal_bag,[dull_indigo_bag,mirrored_gold_bag]).
data(dark_maroon_bag,[dark_turquoise_bag,mirrored_silver_bag,wavy_bronze_bag,clear_turquoise_bag]).
data(wavy_teal_bag,[plaid_fuchsia_bag,drab_orange_bag,vibrant_teal_bag]).
data(muted_lime_bag,[bright_blue_bag,light_salmon_bag]).
data(plaid_plum_bag,[wavy_gold_bag,pale_aqua_bag]).
data(striped_indigo_bag,[faded_black_bag]).
data(clear_lavender_bag,[no_other_bag]).
data(dull_tomato_bag,[dim_lime_bag]).
data(shiny_yellow_bag,[faded_coral_bag,striped_violet_bag,clear_orange_bag]).
data(light_lavender_bag,[dull_maroon_bag]).
data(pale_chartreuse_bag,[clear_green_bag]).
data(posh_turquoise_bag,[striped_olive_bag,bright_chartreuse_bag]).
data(bright_lavender_bag,[dark_white_bag,wavy_coral_bag]).
data(shiny_lavender_bag,[wavy_lime_bag,wavy_bronze_bag]).
data(light_black_bag,[pale_black_bag,pale_purple_bag,drab_lavender_bag]).
data(plaid_maroon_bag,[clear_teal_bag,clear_lavender_bag,dim_chartreuse_bag,vibrant_teal_bag]).
data(striped_cyan_bag,[posh_fuchsia_bag,faded_violet_bag]).
data(striped_lavender_bag,[pale_yellow_bag]).
data(posh_purple_bag,[light_tomato_bag,muted_crimson_bag]).
data(dim_crimson_bag,[wavy_aqua_bag,pale_maroon_bag,faded_bronze_bag]).
data(muted_fuchsia_bag,[striped_gray_bag,posh_gray_bag,clear_white_bag,dotted_orange_bag]).
data(drab_turquoise_bag,[bright_indigo_bag]).
data(vibrant_purple_bag,[mirrored_bronze_bag]).
data(bright_olive_bag,[light_bronze_bag]).
data(shiny_plum_bag,[muted_indigo_bag,light_lime_bag,clear_coral_bag,dim_lavender_bag]).
data(dotted_beige_bag,[plaid_plum_bag,dark_coral_bag,wavy_indigo_bag]).
data(striped_black_bag,[muted_gold_bag]).
data(shiny_orange_bag,[faded_blue_bag,shiny_green_bag]).
data(shiny_coral_bag,[posh_orange_bag,striped_red_bag,muted_yellow_bag,dull_lavender_bag]).
data(vibrant_yellow_bag,[dull_fuchsia_bag,pale_coral_bag,muted_magenta_bag,drab_turquoise_bag]).
data(shiny_gold_bag,[mirrored_crimson_bag,mirrored_tan_bag,drab_green_bag,shiny_silver_bag]).
data(bright_violet_bag,[vibrant_white_bag,clear_green_bag,faded_yellow_bag]).
data(mirrored_tan_bag,[dark_black_bag,clear_green_bag,bright_cyan_bag,faded_bronze_bag]).
data(posh_indigo_bag,[pale_plum_bag,dark_brown_bag,dull_crimson_bag]).
data(pale_indigo_bag,[posh_plum_bag]).
data(drab_tan_bag,[light_gray_bag,drab_orange_bag]).
data(muted_green_bag,[dotted_violet_bag,dotted_cyan_bag]).
data(light_turquoise_bag,[posh_brown_bag]).
data(dotted_blue_bag,[posh_purple_bag,plaid_gray_bag]).
data(plaid_silver_bag,[wavy_maroon_bag,clear_black_bag,shiny_indigo_bag,striped_gold_bag]).
data(dim_plum_bag,[dotted_fuchsia_bag,clear_yellow_bag,striped_red_bag]).
data(dotted_chartreuse_bag,[clear_yellow_bag,dim_red_bag,dim_turquoise_bag,mirrored_orange_bag]).
data(dim_blue_bag,[bright_turquoise_bag,light_blue_bag,wavy_red_bag]).
data(faded_gold_bag,[mirrored_gray_bag,dotted_cyan_bag,mirrored_red_bag,shiny_silver_bag]).
data(dull_fuchsia_bag,[plaid_cyan_bag,shiny_purple_bag]).
data(dotted_coral_bag,[muted_aqua_bag,dark_orange_bag,bright_black_bag]).
data(striped_bronze_bag,[mirrored_purple_bag,wavy_aqua_bag]).
data(faded_silver_bag,[bright_salmon_bag,striped_olive_bag,vibrant_turquoise_bag]).
data(vibrant_white_bag,[muted_crimson_bag,bright_orange_bag,dark_brown_bag]).
data(shiny_fuchsia_bag,[dull_silver_bag,wavy_indigo_bag,shiny_gold_bag,bright_beige_bag]).
data(drab_crimson_bag,[mirrored_purple_bag,clear_magenta_bag,light_indigo_bag,clear_brown_bag]).
data(posh_aqua_bag,[dark_brown_bag,shiny_white_bag]).
data(pale_tomato_bag,[posh_gray_bag,wavy_silver_bag,drab_crimson_bag,dotted_aqua_bag]).
data(wavy_bronze_bag,[plaid_coral_bag]).
data(dull_white_bag,[shiny_magenta_bag,clear_olive_bag,posh_silver_bag,dark_blue_bag]).
data(shiny_aqua_bag,[drab_green_bag,dark_maroon_bag,striped_turquoise_bag,pale_white_bag]).
data(wavy_brown_bag,[faded_gold_bag,bright_aqua_bag,dotted_tan_bag,vibrant_crimson_bag]).
data(clear_black_bag,[dull_orange_bag,posh_fuchsia_bag,mirrored_cyan_bag,shiny_gold_bag]).
data(posh_tomato_bag,[pale_plum_bag]).
data(vibrant_fuchsia_bag,[drab_olive_bag,drab_bronze_bag,dull_blue_bag]).
data(mirrored_lavender_bag,[faded_cyan_bag,mirrored_bronze_bag,faded_tan_bag,clear_cyan_bag]).
data(mirrored_lime_bag,[dull_gray_bag,plaid_beige_bag]).
data(faded_chartreuse_bag,[light_coral_bag]).
data(dim_brown_bag,[pale_yellow_bag,striped_lime_bag]).
data(pale_gold_bag,[striped_plum_bag]).
data(mirrored_chartreuse_bag,[striped_salmon_bag,shiny_teal_bag,wavy_gold_bag,light_magenta_bag]).
data(plaid_white_bag,[faded_orange_bag,dull_tomato_bag,vibrant_olive_bag]).
data(clear_crimson_bag,[posh_maroon_bag,muted_white_bag,dim_fuchsia_bag,pale_maroon_bag]).
data(wavy_tomato_bag,[dim_tan_bag,dim_orange_bag,mirrored_tan_bag,posh_indigo_bag]).
data(dim_coral_bag,[no_other_bag]).
data(plaid_magenta_bag,[clear_gold_bag,posh_orange_bag]).
data(wavy_gold_bag,[plaid_blue_bag,pale_purple_bag,pale_yellow_bag]).
data(wavy_blue_bag,[light_white_bag,pale_magenta_bag,plaid_lime_bag,faded_cyan_bag]).
data(pale_yellow_bag,[vibrant_gray_bag]).
data(clear_chartreuse_bag,[light_gray_bag,dark_tomato_bag]).
data(drab_lavender_bag,[vibrant_salmon_bag]).
data(dark_turquoise_bag,[pale_plum_bag]).
data(vibrant_tan_bag,[plaid_aqua_bag]).
data(vibrant_green_bag,[vibrant_red_bag,vibrant_tomato_bag]).
data(plaid_aqua_bag,[wavy_silver_bag,faded_silver_bag]).
data(pale_brown_bag,[dark_fuchsia_bag,drab_green_bag,bright_cyan_bag]).
data(drab_olive_bag,[dull_maroon_bag,dark_maroon_bag]).
data(wavy_cyan_bag,[muted_blue_bag,clear_beige_bag]).
data(dotted_white_bag,[dull_orange_bag]).
data(shiny_green_bag,[vibrant_gray_bag,vibrant_tomato_bag,dark_violet_bag]).
data(bright_fuchsia_bag,[vibrant_chartreuse_bag,dim_orange_bag,clear_orange_bag,posh_fuchsia_bag]).
data(clear_purple_bag,[dim_gray_bag,shiny_tan_bag]).
data(dotted_lavender_bag,[posh_gray_bag,dull_beige_bag,plaid_beige_bag,dull_teal_bag]).
data(dull_salmon_bag,[muted_magenta_bag,muted_purple_bag,light_teal_bag,vibrant_cyan_bag]).
data(dark_green_bag,[clear_lavender_bag,shiny_silver_bag]).
data(dull_maroon_bag,[dark_fuchsia_bag,mirrored_red_bag,mirrored_gray_bag,dim_lime_bag]).
data(clear_bronze_bag,[dull_turquoise_bag,dim_olive_bag,wavy_violet_bag,dotted_bronze_bag]).
data(muted_silver_bag,[clear_green_bag,shiny_tan_bag]).
data(dark_lavender_bag,[dim_gray_bag,dark_teal_bag]).
data(light_violet_bag,[light_blue_bag,clear_lavender_bag,dim_teal_bag]).
data(vibrant_violet_bag,[posh_plum_bag,dark_fuchsia_bag]).
data(posh_teal_bag,[pale_indigo_bag,plaid_fuchsia_bag,muted_gray_bag]).
data(posh_crimson_bag,[bright_gold_bag]).
data(dark_yellow_bag,[muted_gold_bag,dull_aqua_bag]).
data(drab_gold_bag,[dark_maroon_bag,dim_turquoise_bag,mirrored_cyan_bag]).
data(dotted_tan_bag,[plaid_turquoise_bag,shiny_aqua_bag]).
data(vibrant_indigo_bag,[faded_plum_bag,dark_purple_bag,drab_maroon_bag,dull_teal_bag]).
data(muted_olive_bag,[dull_bronze_bag,drab_salmon_bag,plaid_magenta_bag,mirrored_purple_bag]).
data(plaid_purple_bag,[plaid_turquoise_bag,muted_olive_bag,shiny_crimson_bag]).
data(dim_lime_bag,[mirrored_gray_bag,plaid_magenta_bag,dark_fuchsia_bag,bright_beige_bag]).
data(muted_violet_bag,[bright_aqua_bag,pale_brown_bag,dark_fuchsia_bag]).
data(dark_beige_bag,[vibrant_fuchsia_bag,shiny_white_bag]).
data(dim_gray_bag,[mirrored_violet_bag,plaid_orange_bag,vibrant_olive_bag,pale_white_bag]).
data(pale_cyan_bag,[dark_red_bag,mirrored_beige_bag,shiny_purple_bag,dark_fuchsia_bag]).
data(dim_indigo_bag,[faded_blue_bag,muted_bronze_bag]).
data(shiny_brown_bag,[vibrant_salmon_bag,drab_orange_bag]).
data(dull_black_bag,[shiny_cyan_bag,dark_purple_bag]).
data(light_white_bag,[mirrored_beige_bag,faded_turquoise_bag]).
data(dim_fuchsia_bag,[drab_salmon_bag,striped_gray_bag,light_gray_bag]).
data(striped_gray_bag,[plaid_white_bag,mirrored_purple_bag,vibrant_aqua_bag,muted_indigo_bag]).
data(wavy_lavender_bag,[dotted_cyan_bag,bright_chartreuse_bag,plaid_black_bag,dotted_gold_bag]).
data(dull_blue_bag,[vibrant_olive_bag]).
data(dark_violet_bag,[muted_white_bag,dim_lime_bag]).
data(shiny_maroon_bag,[dotted_violet_bag,shiny_brown_bag,light_blue_bag]).
data(drab_yellow_bag,[shiny_fuchsia_bag]).
data(clear_fuchsia_bag,[wavy_gray_bag,wavy_white_bag,drab_gray_bag,bright_indigo_bag]).
data(plaid_coral_bag,[dull_lime_bag,vibrant_olive_bag,shiny_gold_bag]).
data(dull_beige_bag,[dull_blue_bag,pale_black_bag,dim_coral_bag]).
data(plaid_salmon_bag,[bright_coral_bag,bright_tomato_bag,dim_tan_bag,shiny_purple_bag]).
data(dim_bronze_bag,[posh_teal_bag,pale_salmon_bag]).
data(dull_magenta_bag,[dull_lime_bag,light_gold_bag,striped_purple_bag]).
data(plaid_fuchsia_bag,[dim_lime_bag,bright_cyan_bag,faded_silver_bag,posh_fuchsia_bag]).
data(dark_plum_bag,[plaid_green_bag]).
data(striped_silver_bag,[clear_silver_bag,dotted_orange_bag,striped_fuchsia_bag,posh_bronze_bag]).
data(bright_green_bag,[bright_white_bag,mirrored_lavender_bag,shiny_blue_bag]).
data(wavy_plum_bag,[light_turquoise_bag,shiny_violet_bag,dim_blue_bag]).
data(bright_chartreuse_bag,[dim_gold_bag]).
data(dotted_crimson_bag,[wavy_beige_bag]).
data(dull_bronze_bag,[muted_white_bag,faded_orange_bag,plaid_blue_bag]).
data(dull_crimson_bag,[pale_black_bag,dim_lime_bag,clear_lavender_bag,faded_orange_bag]).
data(striped_red_bag,[shiny_maroon_bag,muted_yellow_bag,faded_lavender_bag,dark_olive_bag]).
data(clear_magenta_bag,[dark_coral_bag]).
data(plaid_beige_bag,[vibrant_purple_bag,drab_salmon_bag,clear_white_bag,dull_olive_bag]).
data(dotted_bronze_bag,[dull_tomato_bag,clear_lime_bag,clear_gold_bag,mirrored_indigo_bag]).
data(pale_black_bag,[faded_bronze_bag,dotted_violet_bag]).
data(faded_purple_bag,[light_fuchsia_bag,dull_violet_bag]).
data(clear_plum_bag,[vibrant_gray_bag,striped_tan_bag]).
data(wavy_black_bag,[mirrored_turquoise_bag]).
data(dark_coral_bag,[faded_violet_bag]).
data(pale_orange_bag,[mirrored_red_bag,clear_olive_bag]).
